-- ---------------------------------
-- Locations
-- ---------------------------------

-- ---------------
-- country: US
-- ---------------

INSERT INTO dbo.Countries (name, approxPopulation)
VALUES
('US', 328200000)

-- ---------------
-- cities (equivalent to US states)
-- ---------------

INSERT INTO dbo.Cities (countryId, [name])
VALUES
(1,'AK'), (1,'AL'), (1,'AR'), (1,'AZ'), (1,'CA'), (1,'CO'), (1,'CT'),
(1,'DE'), (1,'FL'), (1,'GA'), (1,'HI'), (1,'IA'), (1,'ID'), (1,'IL'), (1,'IN'), (1,'KS'),
(1,'KY'), (1,'LA'), (1,'MA'), (1,'MD'), (1,'ME'), (1,'MI'), (1,'MN'), (1,'MO'),
(1,'MS'), (1,'MT'), (1,'NC'), (1,'ND'), (1,'NE'), (1,'NH'), (1,'NJ'), (1,'NM'), (1,'NV'),
(1,'NY'), (1,'OH'), (1,'OK'), (1,'OR'), (1,'PA'), (1,'RI'), (1,'SC'), (1,'SD'), (1,'TN'),
(1,'TX'), (1,'UT'), (1,'VA'), (1,'VT'), (1,'WA'), (1,'WI'), (1,'WV'), (1,'WY')

-- ---------------
-- zones
-- ---------------

INSERT INTO dbo.Zones (cityId, [name])
VALUES
(1, 'Anchorage'),
(1, 'Eagle River'),
(1, 'Fairbanks'),
(1, 'Kenai'),
(1, 'Palmer'),
(2, 'Birmingham'),
(2, 'Greenville'),
(2, 'Haleyville'),
(2, 'Montgomery'),
(2, 'Troy'),
(3, 'Arkadelphia'),
(3, 'Ashdown'),
(3, 'Bella Vista'),
(3, 'Benton'),
(3, 'Bentonville'),
(3, 'Blytheville'),
(3, 'Brinkley'),
(3, 'Bryant'),
(3, 'Cabot'),
(3, 'Conway'),
(3, 'Dardanelle'),
(3, 'Fayetteville'),
(3, 'Fort Smith'),
(3, 'Greenbrier'),
(3, 'Harrison'),
(3, 'Hope'),
(3, 'Hot Springs National Park'),
(3, 'Jacksonville'),
(3, 'Jonesboro'),
(3, 'Little Rock'),
(3, 'Malvern'),
(3, 'Marion'),
(3, 'Mena'),
(3, 'Monticello'),
(3, 'Morrilton'),
(3, 'North Little Rock'),
(3, 'Ozark'),
(3, 'Paragould'),
(3, 'Pea Ridge'),
(3, 'Pine Bluff'),
(3, 'Pocahontas'),
(3, 'Rogers'),
(3, 'Russellville'),
(3, 'Searcy'),
(3, 'Sheridan'),
(3, 'Sherwood'),
(3, 'Springdale'),
(3, 'Texarkana'),
(3, 'Van Buren'),
(3, 'Warren'),
(3, 'West Helena'),
(3, 'West Memphis'),
(3, 'White Hall'),
(4, 'Apache Junction'),
(4, 'Avondale'),
(4, 'Buckeye'),
(4, 'Camp Verde'),
(4, 'Casa Grande'),
(4, 'Cave Creek'),
(4, 'Chandler'),
(4, 'Chino Valley'),
(4, 'Cottonwood'),
(4, 'Douglas'),
(4, 'Eloy'),
(4, 'Flagstaff'),
(4, 'Fountain Hills'),
(4, 'Gilbert'),
(4, 'Glendale'),
(4, 'Goodyear'),
(4, 'Green Valley'),
(4, 'Kingman'),
(4, 'Lake Havasu City'),
(4, 'Litchfield Park'),
(4, 'Marana'),
(4, 'Mesa'),
(4, 'Nogales'),
(4, 'Parker'),
(4, 'Peoria'),
(4, 'Phoenix'),
(4, 'Prescott'),
(4, 'Prescott Valley'),
(4, 'San Manuel'),
(4, 'Scottsdale'),
(4, 'Sedona'),
(4, 'Show Low'),
(4, 'Sierra Vista'),
(4, 'Springerville'),
(4, 'Sun City'),
(4, 'Surprise'),
(4, 'Taylor'),
(4, 'Tempe'),
(4, 'Tucson'),
(4, 'Wickenburg'),
(4, 'Williams'),
(4, 'Winslow'),
(4, 'Yuma'),
(5, 'Agoura Hills'),
(5, 'Alameda'),
(5, 'Albany'),
(5, 'Alhambra'),
(5, 'Alpine'),
(5, 'Altadena'),
(5, 'Alturas'),
(5, 'American Canyon'),
(5, 'Anaheim'),
(5, 'Antelope'),
(5, 'Antioch'),
(5, 'Apple Valley'),
(5, 'Arcadia'),
(5, 'Arcata'),
(5, 'Arroyo Grande'),
(5, 'Artesia'),
(5, 'Atascadero'),
(5, 'Auburn'),
(5, 'Azusa'),
(5, 'Baker'),
(5, 'Bakersfield'),
(5, 'Baldwin Park'),
(5, 'Barstow'),
(5, 'Beaumont'),
(5, 'Bell Gardens'),
(5, 'Bellflower'),
(5, 'Belmont'),
(5, 'Benicia'),
(5, 'Berkeley'),
(5, 'Big Bear Lake'),
(5, 'Bishop'),
(5, 'Bonita'),
(5, 'Brawley'),
(5, 'Brea'),
(5, 'Buellton'),
(5, 'Buena Park'),
(5, 'Burbank'),
(5, 'Burlingame'),
(5, 'Calimesa'),
(5, 'Camarillo'),
(5, 'Campbell'),
(5, 'Canoga Park'),
(5, 'Canyon Country'),
(5, 'Capitola'),
(5, 'Carlsbad'),
(5, 'Carmichael'),
(5, 'Carson'),
(5, 'Castro Valley'),
(5, 'Ceres'),
(5, 'Cerritos'),
(5, 'Chatsworth'),
(5, 'Chico'),
(5, 'Chino'),
(5, 'Chino Hills'),
(5, 'Chula Vista'),
(5, 'Citrus Heights'),
(5, 'Claremont'),
(5, 'Clovis'),
(5, 'Coachella'),
(5, 'Coalinga'),
(5, 'Colton'),
(5, 'Colusa'),
(5, 'Compton'),
(5, 'Concord'),
(5, 'Corcoran'),
(5, 'Corona'),
(5, 'Costa Mesa'),
(5, 'Covina'),
(5, 'Crescent City'),
(5, 'Culver City'),
(5, 'Cupertino'),
(5, 'Cypress'),
(5, 'Daly City'),
(5, 'Dana Point'),
(5, 'Danville'),
(5, 'Davis'),
(5, 'Desert Hot Springs'),
(5, 'Diamond Bar'),
(5, 'Dinuba'),
(5, 'Discovery Bay'),
(5, 'Dixon'),
(5, 'Downey'),
(5, 'Duarte'),
(5, 'Dublin'),
(5, 'El Cajon'),
(5, 'El Centro'),
(5, 'El Cerrito'),
(5, 'El Monte'),
(5, 'El Sobrante'),
(5, 'Elk Grove'),
(5, 'Encinitas'),
(5, 'Encino'),
(5, 'Escondido'),
(5, 'Eureka'),
(5, 'Fair Oaks'),
(5, 'Fairfield'),
(5, 'Fallbrook'),
(5, 'Folsom'),
(5, 'Fontana'),
(5, 'Fortuna'),
(5, 'Fountain Valley'),
(5, 'Freedom'),
(5, 'Fremont'),
(5, 'Fresno'),
(5, 'Fullerton'),
(5, 'Galt'),
(5, 'Garden Grove'),
(5, 'Gardena'),
(5, 'Gilroy'),
(5, 'Glendale'),
(5, 'Glendora'),
(5, 'Goleta'),
(5, 'Gonzales'),
(5, 'Granada Hills'),
(5, 'Granite Bay'),
(5, 'Grover Beach'),
(5, 'Gustine'),
(5, 'Hacienda Heights'),
(5, 'Hanford'),
(5, 'Hawaiian Gardens'),
(5, 'Hawthorne'),
(5, 'Hayward'),
(5, 'Hemet'),
(5, 'Hercules'),
(5, 'Hesperia'),
(5, 'Highland'),
(5, 'Hollister'),
(5, 'Huntington Beach'),
(5, 'Huntington Park'),
(5, 'Imperial Beach'),
(5, 'Indio'),
(5, 'Inglewood'),
(5, 'Irvine'),
(5, 'Jackson'),
(5, 'King City'),
(5, 'Kingsburg'),
(5, 'La Ca√±ada Flintridge'),
(5, 'La Crescenta'),
(5, 'La Habra'),
(5, 'La Mesa'),
(5, 'La Mirada'),
(5, 'La Puente'),
(5, 'La Quinta'),
(5, 'Lafayette'),
(5, 'Laguna Beach'),
(5, 'Laguna Niguel'),
(5, 'Lake Elsinore'),
(5, 'Lake Forest'),
(5, 'Lakeside'),
(5, 'Lakewood'),
(5, 'Lancaster'),
(5, 'Lawndale'),
(5, 'Lebec'),
(5, 'Lemon Grove'),
(5, 'Lincoln'),
(5, 'Livermore'),
(5, 'Lodi'),
(5, 'Loma Linda'),
(5, 'Lomita'),
(5, 'Long Beach'),
(5, 'Los Alamitos'),
(5, 'Los Angeles'),
(5, 'Los Banos'),
(5, 'Los Gatos'),
(5, 'Lynwood'),
(5, 'Manhattan Beach'),
(5, 'Manteca'),
(5, 'Martinez'),
(5, 'Marysville'),
(5, 'Menlo Park'),
(5, 'Merced'),
(5, 'Milpitas'),
(5, 'Mission Viejo'),
(5, 'Modesto'),
(5, 'Montclair'),
(5, 'Montebello'),
(5, 'Monterey'),
(5, 'Monterey Park'),
(5, 'Moraga'),
(5, 'Moreno Valley'),
(5, 'Morgan Hill'),
(5, 'Mountain View'),
(5, 'Murrieta'),
(5, 'Napa'),
(5, 'National City'),
(5, 'Newbury Park'),
(5, 'Newhall'),
(5, 'Newman'),
(5, 'Newport Beach'),
(5, 'Nipomo'),
(5, 'North Highlands'),
(5, 'North Hills'),
(5, 'North Hollywood'),
(5, 'Northridge'),
(5, 'Norwalk'),
(5, 'Oakdale'),
(5, 'Oakland'),
(5, 'Oceanside'),
(5, 'Ontario'),
(5, 'Orange'),
(5, 'Oxnard'),
(5, 'Pacific Grove'),
(5, 'Pacific Palisades'),
(5, 'Palm Desert'),
(5, 'Palmdale'),
(5, 'Palo Alto'),
(5, 'Palos Verdes Peninsula'),
(5, 'Panorama City'),
(5, 'Paramount'),
(5, 'Parlier'),
(5, 'Pasadena'),
(5, 'Perris'),
(5, 'Petaluma'),
(5, 'Pico Rivera'),
(5, 'Pinole'),
(5, 'Pismo Beach'),
(5, 'Pittsburg'),
(5, 'Placentia'),
(5, 'Pleasant Hill'),
(5, 'Pleasanton'),
(5, 'Pomona'),
(5, 'Port Hueneme'),
(5, 'Porterville'),
(5, 'Poway'),
(5, 'Ramona'),
(5, 'Rancho Cordova'),
(5, 'Rancho Cucamonga'),
(5, 'Rancho Santa Margarita'),
(5, 'Red Bluff'),
(5, 'Redding'),
(5, 'Redlands'),
(5, 'Redondo Beach'),
(5, 'Redwood City'),
(5, 'Reseda'),
(5, 'Rialto'),
(5, 'Richmond'),
(5, 'Ripon'),
(5, 'Riverbank'),
(5, 'Riverside'),
(5, 'Rohnert Park'),
(5, 'Rosamond'),
(5, 'Rosemead'),
(5, 'Roseville'),
(5, 'Rowland Heights'),
(5, 'Sacramento'),
(5, 'Saint Helena'),
(5, 'Salida'),
(5, 'Salinas'),
(5, 'San Bernardino'),
(5, 'San Bruno'),
(5, 'San Clemente'),
(5, 'San Diego'),
(5, 'San Dimas'),
(5, 'San Fernando'),
(5, 'San Francisco'),
(5, 'San Jacinto'),
(5, 'San Jose'),
(5, 'San Leandro'),
(5, 'San Luis Obispo'),
(5, 'San Marcos'),
(5, 'San Mateo'),
(5, 'San Pablo'),
(5, 'San Pedro'),
(5, 'San Rafael'),
(5, 'San Ramon'),
(5, 'San Ysidro'),
(5, 'Santa Ana'),
(5, 'Santa Barbara'),
(5, 'Santa Clara'),
(5, 'Santa Clarita'),
(5, 'Santa Cruz'),
(5, 'Santa Fe Springs'),
(5, 'Santa Maria'),
(5, 'Santa Monica'),
(5, 'Santa Paula'),
(5, 'Santa Rosa'),
(5, 'Santee'),
(5, 'Scotts Valley'),
(5, 'Seal Beach'),
(5, 'Seaside'),
(5, 'Sebastopol'),
(5, 'Selma'),
(5, 'Signal Hill'),
(5, 'Simi Valley'),
(5, 'Solana Beach'),
(5, 'Sonoma'),
(5, 'Sonora'),
(5, 'South El Monte'),
(5, 'South Gate'),
(5, 'South San Francisco'),
(5, 'Sun Valley'),
(5, 'Sunland'),
(5, 'Sunnyvale'),
(5, 'Sylmar'),
(5, 'Temecula'),
(5, 'Temple City'),
(5, 'Thousand Oaks'),
(5, 'Torrance'),
(5, 'Tracy'),
(5, 'Tujunga'),
(5, 'Tulare'),
(5, 'Turlock'),
(5, 'Tustin'),
(5, 'Union City'),
(5, 'Upland'),
(5, 'Vacaville'),
(5, 'Valencia'),
(5, 'Vallejo'),
(5, 'Van Nuys'),
(5, 'Venice'),
(5, 'Ventura'),
(5, 'Victorville'),
(5, 'Visalia'),
(5, 'Vista'),
(5, 'Walnut'),
(5, 'Walnut Creek'),
(5, 'Watsonville'),
(5, 'Weed'),
(5, 'West Covina'),
(5, 'West Hills'),
(5, 'West Sacramento'),
(5, 'Westlake Village'),
(5, 'Westminster'),
(5, 'Whittier'),
(5, 'Wildomar'),
(5, 'Willits'),
(5, 'Willows'),
(5, 'Wilmington'),
(5, 'Windsor'),
(5, 'Winnetka'),
(5, 'Woodland'),
(5, 'Woodland Hills'),
(5, 'Yucaipa'),
(5, 'Yucca Valley'),
(6, 'Arvada'),
(6, 'Aurora'),
(6, 'Boulder'),
(6, 'Brighton'),
(6, 'Broomfield'),
(6, 'Brush'),
(6, 'Burlington'),
(6, 'Calhan'),
(6, 'Castle Rock'),
(6, 'Colorado Springs'),
(6, 'Conifer'),
(6, 'Delta'),
(6, 'Denver'),
(6, 'Durango'),
(6, 'Eagle'),
(6, 'Englewood'),
(6, 'Evans'),
(6, 'Evergreen'),
(6, 'Fort Collins'),
(6, 'Fort Lupton'),
(6, 'Grand Junction'),
(6, 'Greeley'),
(6, 'Gunnison'),
(6, 'Henderson'),
(6, 'Johnstown'),
(6, 'Lafayette'),
(6, 'Leadville'),
(6, 'Littleton'),
(6, 'Longmont'),
(6, 'Louisville'),
(6, 'Loveland'),
(6, 'Manitou Springs'),
(6, 'Montrose'),
(6, 'New Castle'),
(6, 'Parker'),
(6, 'Pueblo'),
(6, 'Silverthorne'),
(6, 'Westminster'),
(6, 'Wheat Ridge'),
(6, 'Windsor'),
(7, 'Bridgeport'),
(7, 'Bristol'),
(7, 'Cheshire'),
(7, 'Cos Cob'),
(7, 'Durham'),
(7, 'Enfield'),
(7, 'Fairfield'),
(7, 'Farmington'),
(7, 'Glastonbury'),
(7, 'Greenwich'),
(7, 'Guilford'),
(7, 'Hamden'),
(7, 'Hartford'),
(7, 'Manchester'),
(7, 'Meriden'),
(7, 'Middletown'),
(7, 'Milford'),
(7, 'New Britain'),
(7, 'New Haven'),
(7, 'New London'),
(7, 'Niantic'),
(7, 'North Haven'),
(7, 'Norwalk'),
(7, 'Old Greenwich'),
(7, 'Plainville'),
(7, 'Prospect'),
(7, 'Shelton'),
(7, 'Southington'),
(7, 'Terryville'),
(7, 'Uncasville'),
(7, 'Waterbury'),
(7, 'Windsor'),
(8, 'Bear'),
(8, 'Claymont'),
(8, 'Delmar'),
(8, 'Dover'),
(8, 'Fenwick Island'),
(8, 'Georgetown'),
(8, 'Harrington'),
(8, 'Hockessin'),
(8, 'Lewes'),
(8, 'Middletown'),
(8, 'Millsboro'),
(8, 'New Castle'),
(8, 'Newark'),
(8, 'Seaford'),
(8, 'Selbyville'),
(8, 'Wilmington'),
(9, 'Altamonte Springs'),
(9, 'Apopka'),
(9, 'Arcadia'),
(9, 'Atlantic Beach'),
(9, 'Auburndale'),
(9, 'Avon Park'),
(9, 'Bartow'),
(9, 'Belle Glade'),
(9, 'Boca Raton'),
(9, 'Bonifay'),
(9, 'Boynton Beach'),
(9, 'Bradenton'),
(9, 'Brandon'),
(9, 'Brooksville'),
(9, 'Bushnell'),
(9, 'Cantonment'),
(9, 'Cape Canaveral'),
(9, 'Cape Coral'),
(9, 'Chattahoochee'),
(9, 'Chipley'),
(9, 'Clearwater'),
(9, 'Clearwater Beach'),
(9, 'Clermont'),
(9, 'Cocoa'),
(9, 'Crawfordville'),
(9, 'Crestview'),
(9, 'Daytona Beach'),
(9, 'Deerfield Beach'),
(9, 'DeFuniak Springs'),
(9, 'DeLand'),
(9, 'Delray Beach'),
(9, 'Deltona'),
(9, 'Destin'),
(9, 'Dunedin'),
(9, 'Edgewater'),
(9, 'Estero'),
(9, 'Eustis'),
(9, 'Fort Lauderdale'),
(9, 'Fort Myers'),
(9, 'Fort Pierce'),
(9, 'Fort Walton Beach'),
(9, 'Gainesville'),
(9, 'Graceville'),
(9, 'Greenville'),
(9, 'Gulf Breeze'),
(9, 'Haines City'),
(9, 'Hialeah'),
(9, 'Hobe Sound'),
(9, 'Hollywood'),
(9, 'Inverness'),
(9, 'Jacksonville'),
(9, 'Jacksonville Beach'),
(9, 'Jensen Beach'),
(9, 'Jupiter'),
(9, 'Kissimmee'),
(9, 'Lady Lake'),
(9, 'Lake Mary'),
(9, 'Lake Worth'),
(9, 'Lakeland'),
(9, 'Largo'),
(9, 'Longwood'),
(9, 'Marathon'),
(9, 'Marianna'),
(9, 'Mary Esther'),
(9, 'Melbourne'),
(9, 'Merritt Island'),
(9, 'Miami'),
(9, 'Miami Gardens'),
(9, 'Milton'),
(9, 'Mims'),
(9, 'Miramar Beach'),
(9, 'Mount Dora'),
(9, 'Mulberry'),
(9, 'Naples'),
(9, 'Navarre'),
(9, 'Neptune Beach'),
(9, 'New Port Richey'),
(9, 'New Smyrna Beach'),
(9, 'North Miami Beach'),
(9, 'Ocala'),
(9, 'Okeechobee'),
(9, 'Oldsmar'),
(9, 'Orange City'),
(9, 'Orange Park'),
(9, 'Orlando'),
(9, 'Ormond Beach'),
(9, 'Oviedo'),
(9, 'Palatka'),
(9, 'Palm Bay'),
(9, 'Palm Beach Gardens'),
(9, 'Palm City'),
(9, 'Palmetto'),
(9, 'Panama City'),
(9, 'Panama City Beach'),
(9, 'Parrish'),
(9, 'Pensacola'),
(9, 'Pinellas Park'),
(9, 'Plant City'),
(9, 'Pompano Beach'),
(9, 'Ponte Vedra Beach'),
(9, 'Port Charlotte'),
(9, 'Port Orange'),
(9, 'Port Richey'),
(9, 'Port Saint Lucie'),
(9, 'Quincy'),
(9, 'Saint Augustine'),
(9, 'Saint Cloud'),
(9, 'Saint Petersburg'),
(9, 'Sanford'),
(9, 'Sarasota'),
(9, 'Sebastian'),
(9, 'Sebring'),
(9, 'Seminole'),
(9, 'Spring Hill'),
(9, 'Summerfield'),
(9, 'Sun City Center'),
(9, 'Tallahassee'),
(9, 'Tampa'),
(9, 'Tarpon Springs'),
(9, 'Titusville'),
(9, 'Umatilla'),
(9, 'Valrico'),
(9, 'Venice'),
(9, 'Vero Beach'),
(9, 'Waldo'),
(9, 'Wauchula'),
(9, 'Wellington'),
(9, 'West Palm Beach'),
(9, 'Wildwood'),
(9, 'Winter Haven'),
(9, 'Winter Park'),
(9, 'Winter Springs'),
(9, 'Yulee'),
(10, 'Acworth'),
(10, 'Adairsville'),
(10, 'Adel'),
(10, 'Albany'),
(10, 'Alpharetta'),
(10, 'Alto'),
(10, 'Americus'),
(10, 'Athens'),
(10, 'Atlanta'),
(10, 'Augusta'),
(10, 'Austell'),
(10, 'Barnesville'),
(10, 'Blue Ridge'),
(10, 'Bonaire'),
(10, 'Bowdon'),
(10, 'Brunswick'),
(10, 'Buford'),
(10, 'Calhoun'),
(10, 'Canton'),
(10, 'Carrollton'),
(10, 'Cartersville'),
(10, 'Cedartown'),
(10, 'Centerville'),
(10, 'Chatsworth'),
(10, 'Clarkesville'),
(10, 'Clayton'),
(10, 'Columbus'),
(10, 'Commerce'),
(10, 'Conley'),
(10, 'Conyers'),
(10, 'Cordele'),
(10, 'Cornelia'),
(10, 'Covington'),
(10, 'Cumming'),
(10, 'Dacula'),
(10, 'Dahlonega'),
(10, 'Dallas'),
(10, 'Dalton'),
(10, 'Decatur'),
(10, 'Douglasville'),
(10, 'Dublin'),
(10, 'Duluth'),
(10, 'Eatonton'),
(10, 'Elberton'),
(10, 'Ellijay'),
(10, 'Evans'),
(10, 'Fairburn'),
(10, 'Fayetteville'),
(10, 'Fitzgerald'),
(10, 'Flowery Branch'),
(10, 'Forsyth'),
(10, 'Gainesville'),
(10, 'Greensboro'),
(10, 'Griffin'),
(10, 'Hartwell'),
(10, 'Hawkinsville'),
(10, 'Hephzibah'),
(10, 'Hiawassee'),
(10, 'Hinesville'),
(10, 'Hiram'),
(10, 'Jasper'),
(10, 'Jonesboro'),
(10, 'Kennesaw'),
(10, 'LaGrange'),
(10, 'Lake Park'),
(10, 'Lavonia'),
(10, 'Lawrenceville'),
(10, 'Leesburg'),
(10, 'Lilburn'),
(10, 'Lithia Springs'),
(10, 'Lithonia'),
(10, 'Locust Grove'),
(10, 'Loganville'),
(10, 'Louisville'),
(10, 'Mableton'),
(10, 'Macon'),
(10, 'Madison'),
(10, 'Manchester'),
(10, 'Marietta'),
(10, 'McDonough'),
(10, 'Metter'),
(10, 'Milledgeville'),
(10, 'Millen'),
(10, 'Monroe'),
(10, 'Morrow'),
(10, 'Nashville'),
(10, 'Newnan'),
(10, 'Norcross'),
(10, 'Ocilla'),
(10, 'Peachtree City'),
(10, 'Peachtree Corners'),
(10, 'Perry'),
(10, 'Pooler'),
(10, 'Powder Springs'),
(10, 'Quitman'),
(10, 'Rincon'),
(10, 'Ringgold'),
(10, 'Rock Spring'),
(10, 'Rockmart'),
(10, 'Rome'),
(10, 'Roswell'),
(10, 'Saint Marys'),
(10, 'Sandersville'),
(10, 'Savannah'),
(10, 'Smyrna'),
(10, 'Suwanee'),
(10, 'Swainsboro'),
(10, 'Sylvester'),
(10, 'Thomaston'),
(10, 'Thomasville'),
(10, 'Thomson'),
(10, 'Toccoa'),
(10, 'Trenton'),
(10, 'Tucker'),
(10, 'Valdosta'),
(10, 'Vidalia'),
(10, 'Villa Rica'),
(10, 'Warner Robins'),
(10, 'Waycross'),
(10, 'Woodstock'),
(10, 'Wrens'),
(11, 'Hilo'),
(11, 'Honolulu'),
(11, 'Kahului'),
(11, 'Kailua'),
(11, 'Kapolei'),
(11, 'Kƒ´hei'),
(11, 'Lahaina'),
(11, 'Lihue'),
(11, 'Makawao'),
(11, 'Pahoa'),
(11, 'WahiawƒÅ'),
(11, 'Waianae'),
(11, 'Wailuku'),
(11, 'Waimanalo'),
(12, 'Algona'),
(12, 'Ames'),
(12, 'Ankeny'),
(12, 'Bettendorf'),
(12, 'Burlington'),
(12, 'Cedar Falls'),
(12, 'Cedar Rapids'),
(12, 'Clear Lake'),
(12, 'Clinton'),
(12, 'Coralville'),
(12, 'Council Bluffs'),
(12, 'Creston'),
(12, 'Davenport'),
(12, 'Denison'),
(12, 'Des Moines'),
(12, 'Dubuque'),
(12, 'Evansdale'),
(12, 'Forest City'),
(12, 'Grimes'),
(12, 'Grinnell'),
(12, 'Harlan'),
(12, 'Independence'),
(12, 'Iowa City'),
(12, 'Iowa Falls'),
(12, 'Knoxville'),
(12, 'Le Mars'),
(12, 'Marion'),
(12, 'Marshalltown'),
(12, 'Mason City'),
(12, 'Mount Pleasant'),
(12, 'Mount Vernon'),
(12, 'Muscatine'),
(12, 'Osceola'),
(12, 'Ottumwa'),
(12, 'Percival'),
(12, 'Perry'),
(12, 'Pocahontas'),
(12, 'Sergeant Bluff'),
(12, 'Shelby'),
(12, 'Sioux Center'),
(12, 'Sioux City'),
(12, 'Spirit Lake'),
(12, 'Toledo'),
(12, 'Urbandale'),
(12, 'Waterloo'),
(12, 'West Des Moines'),
(13, 'Blackfoot'),
(13, 'Boise'),
(13, 'Burley'),
(13, 'Caldwell'),
(13, 'Coeur d''Alene'),
(13, 'Eagle'),
(13, 'Emmett'),
(13, 'Garden City'),
(13, 'Heyburn'),
(13, 'Idaho Falls'),
(13, 'Jerome'),
(13, 'Lewiston'),
(13, 'Meridian'),
(13, 'Middleton'),
(13, 'Moscow'),
(13, 'Nampa'),
(13, 'Pocatello'),
(13, 'Ponderay'),
(13, 'Post Falls'),
(13, 'Rexburg'),
(13, 'Rigby'),
(13, 'Ririe'),
(13, 'Soda Springs'),
(13, 'Twin Falls')

INSERT INTO dbo.Zones (cityId, [name])
VALUES
(14, 'Aledo'),
(14, 'Algonquin'),
(14, 'Arlington Heights'),
(14, 'Aurora'),
(14, 'Bartlett'),
(14, 'Belleville'),
(14, 'Belvidere'),
(14, 'Berwyn'),
(14, 'Bethalto'),
(14, 'Bloomington'),
(14, 'Bolingbrook'),
(14, 'Bourbonnais'),
(14, 'Bradley'),
(14, 'Braidwood'),
(14, 'Breese'),
(14, 'Bridgeview'),
(14, 'Burbank'),
(14, 'Calumet City'),
(14, 'Carpentersville'),
(14, 'Cary'),
(14, 'Centralia'),
(14, 'Champaign'),
(14, 'Chicago'),
(14, 'Chicago Heights'),
(14, 'Cicero'),
(14, 'Coal City'),
(14, 'Collinsville'),
(14, 'Colona'),
(14, 'Crest Hill'),
(14, 'Danville'),
(14, 'Darien'),
(14, 'Decatur'),
(14, 'DeKalb'),
(14, 'Des Plaines'),
(14, 'Dixon'),
(14, 'Dolton'),
(14, 'Downers Grove'),
(14, 'Dwight'),
(14, 'East Alton'),
(14, 'East Peoria'),
(14, 'East Saint Louis'),
(14, 'Edwards'),
(14, 'Edwardsville'),
(14, 'Effingham'),
(14, 'El Paso'),
(14, 'Elgin'),
(14, 'Elk Grove Village'),
(14, 'Elmwood Park'),
(14, 'Energy'),
(14, 'Fairview Heights'),
(14, 'Forsyth'),
(14, 'Fox Lake'),
(14, 'Frankfort'),
(14, 'Freeport'),
(14, 'Geneva'),
(14, 'Gibson City'),
(14, 'Glen Carbon'),
(14, 'Glen Ellyn'),
(14, 'Glendale Heights'),
(14, 'Glenview'),
(14, 'Godfrey'),
(14, 'Granite City'),
(14, 'Grayslake'),
(14, 'Gurnee'),
(14, 'Harrisburg'),
(14, 'Highland'),
(14, 'Highland Park'),
(14, 'Hoffman Estates'),
(14, 'Homer'),
(14, 'Homewood'),
(14, 'Hoopeston'),
(14, 'Joliet'),
(14, 'Kankakee'),
(14, 'Lake Zurich'),
(14, 'Lansing'),
(14, 'Lebanon'),
(14, 'Lena'),
(14, 'Libertyville'),
(14, 'Lincoln'),
(14, 'Litchfield'),
(14, 'Lockport'),
(14, 'Loves Park'),
(14, 'Machesney Park'),
(14, 'Macomb'),
(14, 'Mahomet'),
(14, 'Marion'),
(14, 'Mattoon'),
(14, 'McHenry'),
(14, 'Melrose Park'),
(14, 'Midlothian'),
(14, 'Minooka'),
(14, 'Moline'),
(14, 'Monmouth'),
(14, 'Montgomery'),
(14, 'Morrison'),
(14, 'Morton'),
(14, 'Mount Carmel'),
(14, 'Mount Prospect'),
(14, 'Mount Vernon'),
(14, 'Moweaqua'),
(14, 'Mundelein'),
(14, 'Murphysboro'),
(14, 'Naperville'),
(14, 'Neoga'),
(14, 'Newton'),
(14, 'Niles'),
(14, 'Normal'),
(14, 'North Aurora'),
(14, 'North Chicago'),
(14, 'Oak Brook'),
(14, 'Oak Forest'),
(14, 'Oak Lawn'),
(14, 'Oak Park'),
(14, 'Oglesby'),
(14, 'Olney'),
(14, 'Oswego'),
(14, 'Ottawa'),
(14, 'Palatine'),
(14, 'Palos Heights'),
(14, 'Palos Hills'),
(14, 'Paris'),
(14, 'Pekin'),
(14, 'Peoria'),
(14, 'Peru'),
(14, 'Petersburg'),
(14, 'Pittsfield'),
(14, 'Polo'),
(14, 'Pontiac'),
(14, 'Quincy'),
(14, 'Rantoul'),
(14, 'Red Bud'),
(14, 'Richmond'),
(14, 'Richton Park'),
(14, 'Riverside'),
(14, 'Rock Falls'),
(14, 'Rockford'),
(14, 'Rockton'),
(14, 'Rolling Meadows'),
(14, 'Romeoville'),
(14, 'Roscoe'),
(14, 'Round Lake'),
(14, 'Sandwich'),
(14, 'Schaumburg'),
(14, 'Shelbyville'),
(14, 'Skokie'),
(14, 'South Elgin'),
(14, 'South Holland'),
(14, 'Springfield'),
(14, 'Sullivan'),
(14, 'Sycamore'),
(14, 'Taylorville'),
(14, 'Troy'),
(14, 'Tuscola'),
(14, 'Urbana'),
(14, 'Utica'),
(14, 'Vandalia'),
(14, 'Vernon Hills'),
(14, 'Wadsworth'),
(14, 'Washington'),
(14, 'Wauconda'),
(14, 'Waukegan'),
(14, 'West Frankfort'),
(14, 'Westchester'),
(14, 'Wheaton'),
(14, 'Wood River'),
(14, 'Zion'),
(15, 'Anderson'),
(15, 'Angola'),
(15, 'Auburn'),
(15, 'Aurora'),
(15, 'Avon'),
(15, 'Batesville'),
(15, 'Bedford'),
(15, 'Beech Grove'),
(15, 'Bloomington'),
(15, 'Bluffton'),
(15, 'Boonville'),
(15, 'Brazil'),
(15, 'Bremen'),
(15, 'Brownsburg'),
(15, 'Camby'),
(15, 'Carmel'),
(15, 'Chesterton'),
(15, 'Clarksville'),
(15, 'Clinton'),
(15, 'Columbia City'),
(15, 'Columbus'),
(15, 'Connersville'),
(15, 'Corydon'),
(15, 'Crawfordsville'),
(15, 'Elkhart'),
(15, 'Evansville'),
(15, 'Ferdinand'),
(15, 'Fishers'),
(15, 'Fort Wayne'),
(15, 'Franklin'),
(15, 'Gary'),
(15, 'Gas City'),
(15, 'Goshen'),
(15, 'Greencastle'),
(15, 'Greenwood'),
(15, 'Hammond'),
(15, 'Hobart'),
(15, 'Huntington'),
(15, 'Indianapolis'),
(15, 'Jasper'),
(15, 'Jeffersonville'),
(15, 'Kendallville'),
(15, 'Kokomo'),
(15, 'Kouts'),
(15, 'La Porte'),
(15, 'Lafayette'),
(15, 'Lawrenceburg'),
(15, 'Lebanon'),
(15, 'Linton'),
(15, 'Logansport'),
(15, 'Loogootee'),
(15, 'Madison'),
(15, 'Marion'),
(15, 'Martinsville'),
(15, 'Merrillville'),
(15, 'Middlebury'),
(15, 'Mishawaka'),
(15, 'Monticello'),
(15, 'Mooresville'),
(15, 'Muncie'),
(15, 'Munster'),
(15, 'New Albany'),
(15, 'Noblesville'),
(15, 'North Manchester'),
(15, 'North Vernon'),
(15, 'Palmyra'),
(15, 'Plainfield'),
(15, 'Portage'),
(15, 'Rensselaer'),
(15, 'Richmond'),
(15, 'Rome City'),
(15, 'Rushville'),
(15, 'Schererville'),
(15, 'Sellersburg'),
(15, 'Seymour'),
(15, 'Shelbyville'),
(15, 'South Bend'),
(15, 'Syracuse'),
(15, 'Terre Haute'),
(15, 'Valparaiso'),
(15, 'Vincennes'),
(15, 'Wabash'),
(15, 'Warren'),
(15, 'Warsaw'),
(15, 'Washington'),
(15, 'West Lafayette'),
(15, 'Whiteland'),
(15, 'Whitestown'),
(15, 'Whiting'),
(15, 'Winamac'),
(15, 'Winchester'),
(16, 'Andover'),
(16, 'Arkansas City'),
(16, 'Bonner Springs'),
(16, 'Coffeyville'),
(16, 'Dodge City'),
(16, 'El Dorado'),
(16, 'Fort Scott'),
(16, 'Garden City'),
(16, 'Goodland'),
(16, 'Great Bend'),
(16, 'Hays'),
(16, 'Haysville'),
(16, 'Hutchinson'),
(16, 'Independence'),
(16, 'Junction City'),
(16, 'Kansas City'),
(16, 'Lawrence'),
(16, 'Leavenworth'),
(16, 'Lenexa'),
(16, 'Maize'),
(16, 'Manhattan'),
(16, 'Marysville'),
(16, 'McPherson'),
(16, 'Neodesha'),
(16, 'Olathe'),
(16, 'Overland Park'),
(16, 'Pittsburg'),
(16, 'Pratt'),
(16, 'Salina'),
(16, 'Topeka'),
(16, 'Ulysses'),
(16, 'Wichita'),
(17, 'Ashland'),
(17, 'Barbourville'),
(17, 'Benton'),
(17, 'Berea'),
(17, 'Bowling Green'),
(17, 'Campbellsville'),
(17, 'Catlettsburg'),
(17, 'Cave City'),
(17, 'Central City'),
(17, 'Columbia'),
(17, 'Corbin'),
(17, 'Eddyville'),
(17, 'Edmonton'),
(17, 'Elizabethtown'),
(17, 'Ermine'),
(17, 'Florence'),
(17, 'Frankfort'),
(17, 'Franklin'),
(17, 'Georgetown'),
(17, 'Hardinsburg'),
(17, 'Harrodsburg'),
(17, 'Hazard'),
(17, 'Henderson'),
(17, 'Hodgenville'),
(17, 'Hopkinsville'),
(17, 'Irvine'),
(17, 'Kuttawa'),
(17, 'La Grange'),
(17, 'Latonia'),
(17, 'Lebanon'),
(17, 'Leitchfield'),
(17, 'Lexington'),
(17, 'Liberty'),
(17, 'London'),
(17, 'Louisville'),
(17, 'Madisonville'),
(17, 'Mayfield'),
(17, 'Maysville'),
(17, 'Middlesboro'),
(17, 'Monticello'),
(17, 'Morehead'),
(17, 'Morganfield'),
(17, 'Munfordville'),
(17, 'Murray'),
(17, 'Nicholasville'),
(17, 'Olive Hill'),
(17, 'Owensboro'),
(17, 'Paducah'),
(17, 'Paintsville'),
(17, 'Pendleton'),
(17, 'Pikeville'),
(17, 'Prestonsburg'),
(17, 'Princeton'),
(17, 'Prospect'),
(17, 'Radcliff'),
(17, 'Russellville'),
(17, 'Scottsville'),
(17, 'Shelbyville'),
(17, 'Shepherdsville'),
(17, 'Simpsonville'),
(17, 'Smiths Grove'),
(17, 'Somerset'),
(17, 'South Williamson'),
(17, 'Union'),
(17, 'Walton'),
(17, 'Williamsburg'),
(17, 'Winchester'),
(18, 'Alexandria'),
(18, 'Amite'),
(18, 'Arcadia'),
(18, 'Baker'),
(18, 'Bastrop'),
(18, 'Baton Rouge'),
(18, 'Bogalusa'),
(18, 'Bossier City'),
(18, 'Broussard'),
(18, 'Cottonport'),
(18, 'Covington'),
(18, 'Crowley'),
(18, 'Cut Off'),
(18, 'Denham Springs'),
(18, 'DeRidder'),
(18, 'Destrehan'),
(18, 'Eunice'),
(18, 'Farmerville'),
(18, 'Franklinton'),
(18, 'Gonzales'),
(18, 'Gretna'),
(18, 'Hammond'),
(18, 'Harvey'),
(18, 'Haughton'),
(18, 'Houma'),
(18, 'Iowa'),
(18, 'Kenner'),
(18, 'Lafayette'),
(18, 'Lake Charles'),
(18, 'Leesville'),
(18, 'Mandeville'),
(18, 'Mansura'),
(18, 'Many'),
(18, 'Marrero'),
(18, 'Maurice'),
(18, 'Metairie'),
(18, 'Minden'),
(18, 'Monroe'),
(18, 'Morgan City'),
(18, 'Natchitoches'),
(18, 'New Iberia'),
(18, 'New Orleans'),
(18, 'New Roads'),
(18, 'Opelousas'),
(18, 'Pineville'),
(18, 'Plaquemine'),
(18, 'Ponchatoula'),
(18, 'Port Allen'),
(18, 'Port Barre'),
(18, 'Port Sulphur'),
(18, 'Prairieville'),
(18, 'Ruston'),
(18, 'Saint Francisville'),
(18, 'Scott'),
(18, 'Shreveport'),
(18, 'Slidell'),
(18, 'Springhill'),
(18, 'Sulphur'),
(18, 'Thibodaux'),
(18, 'Vacherie'),
(18, 'Vidalia'),
(18, 'Ville Platte'),
(18, 'Vinton'),
(18, 'West Monroe'),
(18, 'Winnfield'),
(18, 'Zachary'),
(19, 'Acton'),
(19, 'Agawam'),
(19, 'Allston'),
(19, 'Arlington'),
(19, 'Attleboro'),
(19, 'Bedford'),
(19, 'Beverly'),
(19, 'Boston'),
(19, 'Braintree'),
(19, 'Bridgewater'),
(19, 'Brighton'),
(19, 'Brockton'),
(19, 'Brookline'),
(19, 'Burlington'),
(19, 'Cambridge'),
(19, 'Charlestown'),
(19, 'Chelmsford'),
(19, 'Chelsea'),
(19, 'Chicopee'),
(19, 'Clinton'),
(19, 'Concord'),
(19, 'Danvers'),
(19, 'Dorchester'),
(19, 'Dorchester Center'),
(19, 'Dracut'),
(19, 'East Wareham'),
(19, 'Easthampton'),
(19, 'Everett'),
(19, 'Fairhaven'),
(19, 'Fall River'),
(19, 'Falmouth'),
(19, 'Fitchburg'),
(19, 'Framingham'),
(19, 'Franklin'),
(19, 'Gardner'),
(19, 'Hanover'),
(19, 'Hingham'),
(19, 'Holyoke'),
(19, 'Hyannis'),
(19, 'Hyde Park'),
(19, 'Jamaica Plain'),
(19, 'Lee'),
(19, 'Lenox'),
(19, 'Leominster'),
(19, 'Lexington'),
(19, 'Littleton'),
(19, 'Lowell'),
(19, 'Lynn'),
(19, 'Malden'),
(19, 'Mansfield'),
(19, 'Marlborough'),
(19, 'Marstons Mills'),
(19, 'Mashpee'),
(19, 'Maynard'),
(19, 'Medford'),
(19, 'Melrose'),
(19, 'Natick'),
(19, 'Needham Heights'),
(19, 'New Bedford'),
(19, 'Newton'),
(19, 'Newton Highlands'),
(19, 'North Adams'),
(19, 'North Andover'),
(19, 'North Billerica'),
(19, 'North Reading'),
(19, 'North Weymouth'),
(19, 'Northampton'),
(19, 'Norwell'),
(19, 'Peabody'),
(19, 'Pittsfield'),
(19, 'Plainville'),
(19, 'Plymouth'),
(19, 'Quincy'),
(19, 'Randolph'),
(19, 'Revere'),
(19, 'Rockport'),
(19, 'Roslindale'),
(19, 'Salem'),
(19, 'Saugus'),
(19, 'Scituate'),
(19, 'Seekonk'),
(19, 'Somerville'),
(19, 'South Yarmouth'),
(19, 'Southampton'),
(19, 'Spencer'),
(19, 'Springfield'),
(19, 'Taunton'),
(19, 'Townsend'),
(19, 'Uxbridge'),
(19, 'Wakefield'),
(19, 'Walpole'),
(19, 'Waltham'),
(19, 'Watertown'),
(19, 'Webster'),
(19, 'West Boylston'),
(19, 'West Bridgewater'),
(19, 'West Springfield'),
(19, 'Westborough'),
(19, 'Westfield'),
(19, 'Whitinsville'),
(19, 'Wilmington'),
(19, 'Winchendon'),
(19, 'Winchester'),
(19, 'Winthrop'),
(19, 'Woburn'),
(19, 'Worcester'),
(20, 'Aberdeen'),
(20, 'Annapolis'),
(20, 'Baltimore'),
(20, 'Bel Air'),
(20, 'Belcamp'),
(20, 'Beltsville'),
(20, 'Berlin'),
(20, 'Bethesda'),
(20, 'Cambridge'),
(20, 'Capitol Heights'),
(20, 'Catonsville'),
(20, 'Chester'),
(20, 'Chestertown'),
(20, 'Clarksville'),
(20, 'College Park'),
(20, 'Columbia'),
(20, 'Crisfield'),
(20, 'Crofton'),
(20, 'Cumberland'),
(20, 'District Heights'),
(20, 'Dundalk'),
(20, 'Edgewater'),
(20, 'Edgewood'),
(20, 'Elkridge'),
(20, 'Elkton'),
(20, 'Ellicott City'),
(20, 'Emmitsburg'),
(20, 'Essex'),
(20, 'Fort George G Meade'),
(20, 'Fort Washington'),
(20, 'Frederick'),
(20, 'Frostburg'),
(20, 'Gambrills'),
(20, 'Germantown'),
(20, 'Glen Burnie'),
(20, 'Grantsville'),
(20, 'Hagerstown'),
(20, 'Hampstead'),
(20, 'Hanover'),
(20, 'Havre de Grace'),
(20, 'Hyattsville'),
(20, 'Jessup'),
(20, 'La Plata'),
(20, 'Laurel'),
(20, 'Lexington Park'),
(20, 'Linthicum Heights'),
(20, 'Middle River'),
(20, 'Millersville'),
(20, 'New Market'),
(20, 'Nottingham'),
(20, 'Odenton'),
(20, 'Owings Mills'),
(20, 'Oxon Hill'),
(20, 'Parkville'),
(20, 'Pasadena'),
(20, 'Perryville'),
(20, 'Phoenix'),
(20, 'Potomac'),
(20, 'Prince Frederick'),
(20, 'Reisterstown'),
(20, 'Rising Sun'),
(20, 'Rockville'),
(20, 'Rosedale'),
(20, 'Salisbury'),
(20, 'Severn'),
(20, 'Severna Park'),
(20, 'Silver Spring'),
(20, 'Solomons'),
(20, 'Sykesville'),
(20, 'Taneytown'),
(20, 'Thurmont'),
(20, 'Towson'),
(20, 'Upper Marlboro'),
(20, 'Waldorf'),
(20, 'Walkersville'),
(20, 'Westernport'),
(20, 'Westminster'),
(20, 'Westover'),
(20, 'Windsor Mill'),
(21, 'Augusta'),
(21, 'Bangor'),
(21, 'Bath'),
(21, 'Belfast'),
(21, 'Biddeford'),
(21, 'Caribou'),
(21, 'Ellsworth'),
(21, 'Farmington'),
(21, 'Kittery'),
(21, 'Lewiston'),
(21, 'Machias'),
(21, 'Palmyra'),
(21, 'Presque Isle'),
(21, 'Sanford'),
(21, 'Scarborough'),
(21, 'Waterville'),
(22, 'Adrian'),
(22, 'Albion'),
(22, 'Allen Park'),
(22, 'Allendale'),
(22, 'Alma'),
(22, 'Alpena'),
(22, 'Ann Arbor'),
(22, 'Auburn'),
(22, 'Auburn Hills'),
(22, 'Bad Axe'),
(22, 'Battle Creek'),
(22, 'Bay City'),
(22, 'Big Rapids'),
(22, 'Birch Run'),
(22, 'Bridgeport'),
(22, 'Bridgman'),
(22, 'Brighton'),
(22, 'Burton'),
(22, 'Cadillac'),
(22, 'Canton'),
(22, 'Cedar Springs'),
(22, 'Centreville'),
(22, 'Charlevoix'),
(22, 'Clare'),
(22, 'Clarkston'),
(22, 'Clinton Township'),
(22, 'Clio'),
(22, 'Coldwater'),
(22, 'Comstock Park'),
(22, 'Curran'),
(22, 'Davison'),
(22, 'Dearborn'),
(22, 'Dearborn Heights'),
(22, 'Detroit'),
(22, 'Dexter'),
(22, 'Dowagiac'),
(22, 'Dundee'),
(22, 'East Lansing'),
(22, 'Eaton Rapids'),
(22, 'Ecorse'),
(22, 'Escanaba'),
(22, 'Farmington'),
(22, 'Fennville'),
(22, 'Fenton'),
(22, 'Flint'),
(22, 'Flushing'),
(22, 'Frankenmuth'),
(22, 'Franklin'),
(22, 'Fraser'),
(22, 'Fremont'),
(22, 'Fruitport'),
(22, 'Grand Blanc'),
(22, 'Grand Haven'),
(22, 'Grand Rapids'),
(22, 'Grandville'),
(22, 'Grass Lake'),
(22, 'Hamilton'),
(22, 'Harrison'),
(22, 'Hartland'),
(22, 'Hazel Park'),
(22, 'Hillsdale'),
(22, 'Holland'),
(22, 'Holly'),
(22, 'Holt'),
(22, 'Houghton Lake'),
(22, 'Howell'),
(22, 'Hudson'),
(22, 'Hudsonville'),
(22, 'Indian River'),
(22, 'Ionia'),
(22, 'Jackson'),
(22, 'Kalamazoo'),
(22, 'Kalkaska'),
(22, 'Keego Harbor'),
(22, 'Lake Orion'),
(22, 'Lansing'),
(22, 'Lapeer'),
(22, 'Lincoln Park'),
(22, 'Livonia'),
(22, 'Lowell'),
(22, 'Macomb'),
(22, 'Manistee'),
(22, 'Marquette'),
(22, 'Marshall'),
(22, 'Marysville'),
(22, 'Melvindale'),
(22, 'Midland'),
(22, 'Monroe'),
(22, 'Montrose'),
(22, 'Mount Pleasant'),
(22, 'Muskegon'),
(22, 'Newaygo'),
(22, 'Niles'),
(22, 'Norway'),
(22, 'Okemos'),
(22, 'Olivet'),
(22, 'Owosso'),
(22, 'Pinconning'),
(22, 'Plainwell'),
(22, 'Plymouth'),
(22, 'Pontiac'),
(22, 'Port Huron'),
(22, 'Portage'),
(22, 'Prudenville'),
(22, 'Redford'),
(22, 'Reed City'),
(22, 'Richland'),
(22, 'Rochester'),
(22, 'Romulus'),
(22, 'Roseville'),
(22, 'Royal Oak'),
(22, 'Saginaw'),
(22, 'Saint Clair Shores'),
(22, 'Saint Johns'),
(22, 'Saint Joseph'),
(22, 'Sandusky'),
(22, 'Saugatuck'),
(22, 'Sawyer'),
(22, 'South Haven'),
(22, 'South Lyon'),
(22, 'Southfield'),
(22, 'Swartz Creek'),
(22, 'Taylor'),
(22, 'Tecumseh'),
(22, 'Traverse City'),
(22, 'Trenton'),
(22, 'Troy'),
(22, 'Union City'),
(22, 'Utica'),
(22, 'Walled Lake'),
(22, 'Warren'),
(22, 'Waterford'),
(22, 'Wayne'),
(22, 'West Branch'),
(22, 'Westland'),
(22, 'White Lake'),
(22, 'Whitehall'),
(22, 'Whitmore Lake'),
(22, 'Wixom'),
(22, 'Wyandotte'),
(22, 'Wyoming'),
(22, 'Ypsilanti'),
(22, 'Zeeland'),
(23, 'Albert Lea'),
(23, 'Albertville'),
(23, 'Alexandria'),
(23, 'Andover'),
(23, 'Anoka'),
(23, 'Austin'),
(23, 'Avon'),
(23, 'Baxter'),
(23, 'Becker'),
(23, 'Blue Earth'),
(23, 'Brainerd'),
(23, 'Burnsville'),
(23, 'Byron'),
(23, 'Cambridge'),
(23, 'Champlin'),
(23, 'Chanhassen'),
(23, 'Chaska'),
(23, 'Circle Pines'),
(23, 'Cloquet'),
(23, 'Detroit Lakes'),
(23, 'Duluth'),
(23, 'Eden Prairie'),
(23, 'Eveleth'),
(23, 'Faribault'),
(23, 'Fergus Falls'),
(23, 'Forest Lake'),
(23, 'Grand Rapids'),
(23, 'Hinckley'),
(23, 'Hopkins'),
(23, 'Hutchinson'),
(23, 'Inver Grove Heights'),
(23, 'Jordan'),
(23, 'Lake City'),
(23, 'Lindstrom'),
(23, 'Little Falls'),
(23, 'Mankato'),
(23, 'Maple Grove'),
(23, 'Marshall'),
(23, 'Minneapolis'),
(23, 'Montevideo'),
(23, 'Monticello'),
(23, 'Moorhead'),
(23, 'Mora'),
(23, 'Morris'),
(23, 'Norwood Young America'),
(23, 'Osseo'),
(23, 'Owatonna'),
(23, 'Princeton'),
(23, 'Red Wing'),
(23, 'Redwood Falls'),
(23, 'Rochester'),
(23, 'Rogers'),
(23, 'Saint Cloud'),
(23, 'Saint Francis'),
(23, 'Saint James'),
(23, 'Saint Joseph'),
(23, 'Saint Paul'),
(23, 'Saint Peter'),
(23, 'Savage'),
(23, 'Shakopee'),
(23, 'South Saint Paul'),
(23, 'Spicer'),
(23, 'Thief River Falls'),
(23, 'Two Harbors'),
(23, 'Virginia'),
(23, 'Wabasha'),
(23, 'Waconia'),
(23, 'Wadena'),
(23, 'Walker'),
(23, 'Waseca'),
(23, 'Wayzata'),
(23, 'Willmar'),
(23, 'Worthington'),
(23, 'Wyoming'),
(24, 'Arnold'),
(24, 'Ashland'),
(24, 'Ballwin'),
(24, 'Belton'),
(24, 'Blue Springs'),
(24, 'Boonville'),
(24, 'Bowling Green'),
(24, 'Branson'),
(24, 'Bridgeton'),
(24, 'Butler'),
(24, 'Cape Girardeau'),
(24, 'Chesterfield'),
(24, 'Chillicothe'),
(24, 'Columbia'),
(24, 'Cuba'),
(24, 'De Soto'),
(24, 'Dexter'),
(24, 'El Dorado Springs'),
(24, 'Eureka'),
(24, 'Farmington'),
(24, 'Fenton'),
(24, 'Festus'),
(24, 'Florissant'),
(24, 'Grandview'),
(24, 'Hannibal'),
(24, 'Harrisonville'),
(24, 'Hazelwood'),
(24, 'Herculaneum'),
(24, 'Hollister'),
(24, 'House Springs'),
(24, 'Houston'),
(24, 'Independence'),
(24, 'Jefferson City'),
(24, 'Kansas City'),
(24, 'Kingdom City'),
(24, 'Kirksville'),
(24, 'Lake Saint Louis'),
(24, 'Liberty'),
(24, 'Maryland Heights'),
(24, 'Monett'),
(24, 'Mount Vernon'),
(24, 'Mountain Grove'),
(24, 'Neosho'),
(24, 'O Fallon'),
(24, 'Pacific'),
(24, 'Park Hills'),
(24, 'Perryville'),
(24, 'Rolla'),
(24, 'Saint Charles'),
(24, 'Saint Clair'),
(24, 'Saint Joseph'),
(24, 'Saint Louis'),
(24, 'Saint Peters'),
(24, 'Saint Robert'),
(24, 'Sedalia'),
(24, 'Springfield'),
(24, 'Union'),
(24, 'Warrensburg'),
(24, 'Warrenton'),
(24, 'Waynesville'),
(24, 'Wentzville'),
(24, 'West Plains'),
(25, 'Amory'),
(25, 'Bay Saint Louis'),
(25, 'Biloxi'),
(25, 'Brandon'),
(25, 'Brookhaven'),
(25, 'Calhoun City'),
(25, 'Clarksdale'),
(25, 'Cleveland'),
(25, 'Columbus'),
(25, 'Gulfport'),
(25, 'Hattiesburg'),
(25, 'Hernando'),
(25, 'Horn Lake'),
(25, 'Jackson'),
(25, 'Monticello'),
(25, 'Moss Point'),
(25, 'Natchez'),
(25, 'Ocean Springs'),
(25, 'Olive Branch'),
(25, 'Oxford'),
(25, 'Pascagoula'),
(25, 'Pearl'),
(25, 'Pelahatchie'),
(25, 'Pontotoc'),
(25, 'Ridgeland'),
(25, 'Southaven'),
(25, 'Tupelo'),
(26, 'Billings'),
(26, 'Bozeman'),
(26, 'Butte'),
(26, 'Corvallis'),
(26, 'Cut Bank'),
(26, 'Deer Lodge'),
(26, 'Glendive'),
(26, 'Great Falls'),
(26, 'Havre'),
(26, 'Helena'),
(26, 'Kalispell'),
(26, 'Laurel'),
(26, 'Libby'),
(26, 'Livingston'),
(26, 'Missoula'),
(26, 'Polson'),
(26, 'Whitefish')

INSERT INTO dbo.Zones (cityId, [name])
VALUES
(27, 'Aberdeen'),
(27, 'Apex'),
(27, 'Asheboro'),
(27, 'Asheville'),
(27, 'Battleboro'),
(27, 'Belmont'),
(27, 'Black Mountain'),
(27, 'Bladenboro'),
(27, 'Boone'),
(27, 'Bryson City'),
(27, 'Burlington'),
(27, 'Cameron'),
(27, 'Candler'),
(27, 'Canton'),
(27, 'Carthage'),
(27, 'Cary'),
(27, 'Chadbourn'),
(27, 'Chapel Hill'),
(27, 'Charlotte'),
(27, 'Clemmons'),
(27, 'Concord'),
(27, 'Conover'),
(27, 'Cornelius'),
(27, 'Dunn'),
(27, 'Durham'),
(27, 'Eden'),
(27, 'Elizabeth City'),
(27, 'Elizabethtown'),
(27, 'Erwin'),
(27, 'Farmville'),
(27, 'Fayetteville'),
(27, 'Garner'),
(27, 'Gastonia'),
(27, 'Goldsboro'),
(27, 'Graham'),
(27, 'Greensboro'),
(27, 'Greenville'),
(27, 'Hayesville'),
(27, 'Hendersonville'),
(27, 'Hickory'),
(27, 'High Point'),
(27, 'Horse Shoe'),
(27, 'Indian Trail'),
(27, 'Jacksonville'),
(27, 'Jefferson'),
(27, 'Jonesville'),
(27, 'Kannapolis'),
(27, 'Kenly'),
(27, 'Kernersville'),
(27, 'Kings Mountain'),
(27, 'Kinston'),
(27, 'Lenoir'),
(27, 'Lewisville'),
(27, 'Lexington'),
(27, 'Lincolnton'),
(27, 'Louisburg'),
(27, 'Lumberton'),
(27, 'Mars Hill'),
(27, 'Matthews'),
(27, 'Mebane'),
(27, 'Mocksville'),
(27, 'Mooresville'),
(27, 'Morehead City'),
(27, 'Morganton'),
(27, 'Morrisville'),
(27, 'Mount Airy'),
(27, 'Murphy'),
(27, 'Nashville'),
(27, 'New Bern'),
(27, 'Newland'),
(27, 'Newton'),
(27, 'Pfafftown'),
(27, 'Pineville'),
(27, 'Raleigh'),
(27, 'Randleman'),
(27, 'Red Springs'),
(27, 'Roanoke Rapids'),
(27, 'Rockingham'),
(27, 'Rocky Mount'),
(27, 'Rolesville'),
(27, 'Roxboro'),
(27, 'Rutherfordton'),
(27, 'Salisbury'),
(27, 'Sanford'),
(27, 'Scotland Neck'),
(27, 'Shallotte'),
(27, 'Shelby'),
(27, 'Siler City'),
(27, 'Smithfield'),
(27, 'Snow Hill'),
(27, 'Southern Pines'),
(27, 'Sparta'),
(27, 'Spring Lake'),
(27, 'Sylva'),
(27, 'Tarboro'),
(27, 'Thomasville'),
(27, 'Troutman'),
(27, 'Wadesboro'),
(27, 'Wake Forest'),
(27, 'Waynesville'),
(27, 'Wendell'),
(27, 'Whitsett'),
(27, 'Whittier'),
(27, 'Wilmington'),
(27, 'Wilson'),
(27, 'Windsor'),
(27, 'Winston-Salem'),
(27, 'Winterville'),
(27, 'Zebulon'),
(28, 'Bismarck'),
(28, 'Devils Lake'),
(28, 'Dickinson'),
(28, 'Fargo'),
(28, 'Grand Forks'),
(28, 'Jamestown'),
(28, 'Minot'),
(28, 'Valley City'),
(28, 'Wahpeton'),
(28, 'West Fargo'),
(28, 'Williston'),
(29, 'Albion'),
(29, 'Alliance'),
(29, 'Arapahoe'),
(29, 'Auburn'),
(29, 'Beatrice'),
(29, 'Bellevue'),
(29, 'Blair'),
(29, 'Chadron'),
(29, 'Columbus'),
(29, 'Crete'),
(29, 'Fremont'),
(29, 'Grand Island'),
(29, 'Gretna'),
(29, 'Hebron'),
(29, 'Kearney'),
(29, 'La Vista'),
(29, 'Lexington'),
(29, 'Lincoln'),
(29, 'Louisville'),
(29, 'Norfolk'),
(29, 'North Platte'),
(29, 'Ogallala'),
(29, 'Omaha'),
(29, 'Plattsmouth'),
(29, 'Scottsbluff'),
(29, 'Seward'),
(29, 'South Sioux City'),
(29, 'Wahoo'),
(29, 'York'),
(30, 'Claremont'),
(30, 'Concord'),
(30, 'Derry'),
(30, 'Exeter'),
(30, 'Hampton'),
(30, 'Hooksett'),
(30, 'Keene'),
(30, 'Laconia'),
(30, 'Manchester'),
(30, 'Nashua'),
(30, 'Plymouth'),
(30, 'Rochester'),
(30, 'Salem'),
(30, 'Seabrook'),
(30, 'Windham'),
(31, 'Belmar'),
(31, 'Bergenfield'),
(31, 'Blackwood'),
(31, 'Bound Brook'),
(31, 'Brick'),
(31, 'Bridgeton'),
(31, 'Budd Lake'),
(31, 'Burlington'),
(31, 'Camden'),
(31, 'Cape May Court House'),
(31, 'Cedar Knolls'),
(31, 'Clementon'),
(31, 'Columbia'),
(31, 'Cranford'),
(31, 'East Brunswick'),
(31, 'East Hanover'),
(31, 'East Orange'),
(31, 'Eatontown'),
(31, 'Edison'),
(31, 'Elmwood Park'),
(31, 'Englewood'),
(31, 'Englishtown'),
(31, 'Flemington'),
(31, 'Franklin Park'),
(31, 'Garwood'),
(31, 'Glassboro'),
(31, 'Haddon Heights'),
(31, 'Hammonton'),
(31, 'Harrison'),
(31, 'Hasbrouck Heights'),
(31, 'Hawthorne'),
(31, 'Hightstown'),
(31, 'Hillsborough'),
(31, 'Howell'),
(31, 'Jersey City'),
(31, 'Kearny'),
(31, 'Lake Hopatcong'),
(31, 'Lavallette'),
(31, 'Livingston'),
(31, 'Long Branch'),
(31, 'Magnolia'),
(31, 'Manasquan'),
(31, 'Metuchen'),
(31, 'Monmouth Junction'),
(31, 'Moorestown'),
(31, 'Morristown'),
(31, 'Mount Ephraim'),
(31, 'Mount Holly'),
(31, 'Mount Laurel'),
(31, 'Mullica Hill'),
(31, 'New Brunswick'),
(31, 'New Milford'),
(31, 'Newark'),
(31, 'Newton'),
(31, 'North Arlington'),
(31, 'North Bergen'),
(31, 'North Brunswick'),
(31, 'Norwood'),
(31, 'Nutley'),
(31, 'Ocean City'),
(31, 'Paramus'),
(31, 'Parlin'),
(31, 'Pemberton'),
(31, 'Pennsauken'),
(31, 'Pequannock'),
(31, 'Perth Amboy'),
(31, 'Piscataway'),
(31, 'Plainfield'),
(31, 'Point Pleasant Beach'),
(31, 'Rahway'),
(31, 'Red Bank'),
(31, 'Riverton'),
(31, 'Rockaway'),
(31, 'Rutherford'),
(31, 'Saddle Brook'),
(31, 'Secaucus'),
(31, 'Short Hills'),
(31, 'Sicklerville'),
(31, 'Somers Point'),
(31, 'Succasunna'),
(31, 'Toms River'),
(31, 'Trenton'),
(31, 'Union'),
(31, 'Wayne'),
(31, 'West Berlin'),
(31, 'Williamstown'),
(31, 'Woodbridge'),
(32, 'Alamogordo'),
(32, 'Albuquerque'),
(32, 'Aztec'),
(32, 'Bayard'),
(32, 'Belen'),
(32, 'Carlsbad'),
(32, 'Clovis'),
(32, 'Deming'),
(32, 'Espa√±ola'),
(32, 'Farmington'),
(32, 'Grants'),
(32, 'Hobbs'),
(32, 'Las Cruces'),
(32, 'Las Vegas'),
(32, 'Lordsburg'),
(32, 'Los Alamos'),
(32, 'Los Lunas'),
(32, 'Raton'),
(32, 'Rio Rancho'),
(32, 'Roswell'),
(32, 'Santa Fe'),
(33, 'Boulder City'),
(33, 'Carson City'),
(33, 'Dayton'),
(33, 'Elko'),
(33, 'Henderson'),
(33, 'Las Vegas'),
(33, 'Laughlin'),
(33, 'Minden'),
(33, 'North Las Vegas'),
(33, 'Reno'),
(33, 'Sparks'),
(33, 'Sun Valley'),
(34, 'Albany'),
(34, 'Alden'),
(34, 'Amityville'),
(34, 'Arcade'),
(34, 'Astoria'),
(34, 'Auburn'),
(34, 'Baldwin'),
(34, 'Bay Shore'),
(34, 'Bellmore'),
(34, 'Binghamton'),
(34, 'Bronx'),
(34, 'Brooklyn'),
(34, 'Buffalo'),
(34, 'Centereach'),
(34, 'Central Islip'),
(34, 'Chester'),
(34, 'Churchville'),
(34, 'Cicero'),
(34, 'Clifton Park'),
(34, 'Cobleskill'),
(34, 'Commack'),
(34, 'Coram'),
(34, 'Corning'),
(34, 'Corona'),
(34, 'Cortland'),
(34, 'Dansville'),
(34, 'Depew'),
(34, 'Dover Plains'),
(34, 'East Aurora'),
(34, 'East Meadow'),
(34, 'East Northport'),
(34, 'East Syracuse'),
(34, 'Elmhurst'),
(34, 'Elmont'),
(34, 'Endicott'),
(34, 'Fairport'),
(34, 'Far Rockaway'),
(34, 'Farmingdale'),
(34, 'Fayetteville'),
(34, 'Forest Hills'),
(34, 'Frankfort'),
(34, 'Franklin Square'),
(34, 'Fredonia'),
(34, 'Fresh Meadows'),
(34, 'Fulton'),
(34, 'Geneva'),
(34, 'Glen Cove'),
(34, 'Gloversville'),
(34, 'Greenvale'),
(34, 'Hamburg'),
(34, 'Hancock'),
(34, 'Hempstead'),
(34, 'Hicksville'),
(34, 'Hollis'),
(34, 'Horseheads'),
(34, 'Ithaca'),
(34, 'Jamaica'),
(34, 'Jamestown'),
(34, 'Jericho'),
(34, 'Johnson City'),
(34, 'Johnstown'),
(34, 'Kingston'),
(34, 'Lakewood'),
(34, 'Latham'),
(34, 'Le Roy'),
(34, 'Levittown'),
(34, 'Liberty'),
(34, 'Lindenhurst'),
(34, 'Liverpool'),
(34, 'Lockport'),
(34, 'Long Beach'),
(34, 'Lynbrook'),
(34, 'Manorville'),
(34, 'Melville'),
(34, 'Merrick'),
(34, 'Middletown'),
(34, 'Monroe'),
(34, 'Montgomery'),
(34, 'Mount Kisco'),
(34, 'Mount Vernon'),
(34, 'New City'),
(34, 'New Hyde Park'),
(34, 'New Paltz'),
(34, 'New York'),
(34, 'Niagara Falls'),
(34, 'North Babylon'),
(34, 'North Tonawanda'),
(34, 'Northport'),
(34, 'Norwich'),
(34, 'Oceanside'),
(34, 'Olean'),
(34, 'Oneida'),
(34, 'Oneonta'),
(34, 'Orchard Park'),
(34, 'Oswego'),
(34, 'Ozone Park'),
(34, 'Patchogue'),
(34, 'Peekskill'),
(34, 'Pittsford'),
(34, 'Plainview'),
(34, 'Plattsburgh'),
(34, 'Pleasantville'),
(34, 'Pomona'),
(34, 'Port Chester'),
(34, 'Port Washington'),
(34, 'Poughkeepsie'),
(34, 'Pulaski'),
(34, 'Queensbury'),
(34, 'Rego Park'),
(34, 'Rensselaer'),
(34, 'Ridge'),
(34, 'Riverhead'),
(34, 'Rochester'),
(34, 'Rockville Centre'),
(34, 'Rome'),
(34, 'Roosevelt'),
(34, 'Saint James'),
(34, 'Saratoga Springs'),
(34, 'Saugerties'),
(34, 'Schenectady'),
(34, 'Seaford'),
(34, 'Selden'),
(34, 'Sherburne'),
(34, 'South Ozone Park'),
(34, 'Springville'),
(34, 'Syracuse'),
(34, 'Ticonderoga'),
(34, 'Tonawanda'),
(34, 'Troy'),
(34, 'Uniondale'),
(34, 'Utica'),
(34, 'Vestal'),
(34, 'Walden'),
(34, 'Walton'),
(34, 'Watertown'),
(34, 'Webster'),
(34, 'Weedsport'),
(34, 'Wellsville'),
(34, 'West Haverstraw'),
(34, 'West Islip'),
(34, 'West Nyack'),
(34, 'Westbury'),
(34, 'Whitestone'),
(34, 'Whitney Point'),
(34, 'Windsor'),
(34, 'Yonkers'),
(34, 'Yorkville'),
(35, 'Akron'),
(35, 'Alliance'),
(35, 'Amelia'),
(35, 'Ashland'),
(35, 'Athens'),
(35, 'Aurora'),
(35, 'Avon Lake'),
(35, 'Barberton'),
(35, 'Batavia'),
(35, 'Bedford'),
(35, 'Bellefontaine'),
(35, 'Blacklick'),
(35, 'Broadview Heights'),
(35, 'Brookville'),
(35, 'Brunswick'),
(35, 'Bryan'),
(35, 'Bucyrus'),
(35, 'Burbank'),
(35, 'Byesville'),
(35, 'Cambridge'),
(35, 'Canal Winchester'),
(35, 'Canton'),
(35, 'Chardon'),
(35, 'Chillicothe'),
(35, 'Cincinnati'),
(35, 'Circleville'),
(35, 'Cleveland'),
(35, 'Columbus'),
(35, 'Coshocton'),
(35, 'Cuyahoga Falls'),
(35, 'Dayton'),
(35, 'Defiance'),
(35, 'Delaware'),
(35, 'Dresden'),
(35, 'Dublin'),
(35, 'East Liverpool'),
(35, 'Elyria'),
(35, 'Englewood'),
(35, 'Fairborn'),
(35, 'Fairfield'),
(35, 'Findlay'),
(35, 'Fostoria'),
(35, 'Fremont'),
(35, 'Gallipolis'),
(35, 'Geneva'),
(35, 'Georgetown'),
(35, 'Girard'),
(35, 'Grafton'),
(35, 'Greenville'),
(35, 'Grove City'),
(35, 'Hamilton'),
(35, 'Harrison'),
(35, 'Hartville'),
(35, 'Hilliard'),
(35, 'Holland'),
(35, 'Huron'),
(35, 'Independence'),
(35, 'Jackson'),
(35, 'Jeffersonville'),
(35, 'Johnstown'),
(35, 'Kenton'),
(35, 'Lancaster'),
(35, 'Lebanon'),
(35, 'Lewis Center'),
(35, 'Lima'),
(35, 'Logan'),
(35, 'London'),
(35, 'Louisville'),
(35, 'Madison'),
(35, 'Maineville'),
(35, 'Mansfield'),
(35, 'Marengo'),
(35, 'Marion'),
(35, 'Martins Ferry'),
(35, 'Marysville'),
(35, 'Mason'),
(35, 'Massillon'),
(35, 'Maumee'),
(35, 'Medina'),
(35, 'Mentor'),
(35, 'Miamisburg'),
(35, 'Middlefield'),
(35, 'Middletown'),
(35, 'Milford'),
(35, 'Millersburg'),
(35, 'Mount Gilead'),
(35, 'Mount Orab'),
(35, 'Napoleon'),
(35, 'New Albany'),
(35, 'New Lexington'),
(35, 'New Philadelphia'),
(35, 'Newark'),
(35, 'Newton Falls'),
(35, 'Niles'),
(35, 'North Canton'),
(35, 'North Lima'),
(35, 'North Olmsted'),
(35, 'North Royalton'),
(35, 'Northwood'),
(35, 'Oberlin'),
(35, 'Olmsted Falls'),
(35, 'Oregon'),
(35, 'Ottawa'),
(35, 'Oxford'),
(35, 'Painesville'),
(35, 'Pataskala'),
(35, 'Perrysburg'),
(35, 'Pickerington'),
(35, 'Piqua'),
(35, 'Portsmouth'),
(35, 'Powell'),
(35, 'Ravenna'),
(35, 'Reynoldsburg'),
(35, 'Rossford'),
(35, 'Saint Clairsville'),
(35, 'Saint Marys'),
(35, 'Sandusky'),
(35, 'Sidney'),
(35, 'South Point'),
(35, 'Springboro'),
(35, 'Springfield'),
(35, 'Sugarcreek'),
(35, 'Swanton'),
(35, 'Sylvania'),
(35, 'Tallmadge'),
(35, 'Tiffin'),
(35, 'Toledo'),
(35, 'Toronto'),
(35, 'Trenton'),
(35, 'Troy'),
(35, 'Twinsburg'),
(35, 'Uniontown'),
(35, 'Upper Sandusky'),
(35, 'Urbana'),
(35, 'Vandalia'),
(35, 'Vermilion'),
(35, 'Wadsworth'),
(35, 'Wapakoneta'),
(35, 'Warren'),
(35, 'Washington Court House'),
(35, 'Waterville'),
(35, 'Wauseon'),
(35, 'Waverly'),
(35, 'Waynesville'),
(35, 'West Chester'),
(35, 'West Salem'),
(35, 'Westerville'),
(35, 'Wheelersburg'),
(35, 'Whitehouse'),
(35, 'Wickliffe'),
(35, 'Willoughby'),
(35, 'Wilmington'),
(35, 'Wooster'),
(35, 'Xenia'),
(35, 'Youngstown'),
(35, 'Zanesville'),
(36, 'Ada'),
(36, 'Ardmore'),
(36, 'Atoka'),
(36, 'Bartlesville'),
(36, 'Bixby'),
(36, 'Blackwell'),
(36, 'Bristow'),
(36, 'Broken Arrow'),
(36, 'Broken Bow'),
(36, 'Calera'),
(36, 'Catoosa'),
(36, 'Checotah'),
(36, 'Chickasha'),
(36, 'Claremore'),
(36, 'Cleveland'),
(36, 'Comanche'),
(36, 'Davis'),
(36, 'Drumright'),
(36, 'Duncan'),
(36, 'Durant'),
(36, 'Edmond'),
(36, 'Elk City'),
(36, 'Enid'),
(36, 'Glenpool'),
(36, 'Guthrie'),
(36, 'Harrah'),
(36, 'Healdton'),
(36, 'Henryetta'),
(36, 'Hobart'),
(36, 'Lawton'),
(36, 'Mangum'),
(36, 'McAlester'),
(36, 'Miami'),
(36, 'Muskogee'),
(36, 'Mustang'),
(36, 'Norman'),
(36, 'Oklahoma City'),
(36, 'Okmulgee'),
(36, 'Owasso'),
(36, 'Perry'),
(36, 'Piedmont'),
(36, 'Pocola'),
(36, 'Poteau'),
(36, 'Pryor'),
(36, 'Roland'),
(36, 'Sallisaw'),
(36, 'Sapulpa'),
(36, 'Shawnee'),
(36, 'Skiatook'),
(36, 'Spiro'),
(36, 'Sulphur'),
(36, 'Tecumseh'),
(36, 'Tulsa'),
(36, 'Vinita'),
(36, 'Wagoner'),
(36, 'Weatherford'),
(36, 'Wilburton'),
(36, 'Woodward'),
(36, 'Yukon'),
(37, 'Albany'),
(37, 'Ashland'),
(37, 'Astoria'),
(37, 'Beaverton'),
(37, 'Bend'),
(37, 'Canby'),
(37, 'Coos Bay'),
(37, 'Corvallis'),
(37, 'Cottage Grove'),
(37, 'Eugene'),
(37, 'Florence'),
(37, 'Gladstone'),
(37, 'Grants Pass'),
(37, 'Gresham'),
(37, 'Happy Valley'),
(37, 'Hermiston'),
(37, 'Hood River'),
(37, 'Independence'),
(37, 'John Day'),
(37, 'Junction City'),
(37, 'Klamath Falls'),
(37, 'La Grande'),
(37, 'Lake Oswego'),
(37, 'Lincoln City'),
(37, 'McMinnville'),
(37, 'Medford'),
(37, 'Molalla'),
(37, 'Newberg'),
(37, 'Newport'),
(37, 'North Bend'),
(37, 'Oakland'),
(37, 'Oakridge'),
(37, 'Ontario'),
(37, 'Oregon City'),
(37, 'Pendleton'),
(37, 'Portland'),
(37, 'Redmond'),
(37, 'Roseburg'),
(37, 'Salem'),
(37, 'Sandy'),
(37, 'Springfield'),
(37, 'The Dalles'),
(37, 'Troutdale'),
(37, 'Tualatin'),
(37, 'Warrenton'),
(37, 'West Linn'),
(37, 'White City'),
(37, 'Wilsonville'),
(37, 'Woodburn'),
(38, 'Abington'),
(38, 'Aliquippa'),
(38, 'Allentown'),
(38, 'Allison Park'),
(38, 'Altoona'),
(38, 'Ardmore'),
(38, 'Beaver Falls'),
(38, 'Belle Vernon'),
(38, 'Bensalem'),
(38, 'Bentleyville'),
(38, 'Berlin'),
(38, 'Berwick'),
(38, 'Bethel Park'),
(38, 'Bethlehem'),
(38, 'Bloomsburg'),
(38, 'Bradford'),
(38, 'Breezewood'),
(38, 'Breinigsville'),
(38, 'Bridgeville'),
(38, 'Bristol'),
(38, 'Brookhaven'),
(38, 'Brookville'),
(38, 'Burnham'),
(38, 'Butler'),
(38, 'Camp Hill'),
(38, 'Canonsburg'),
(38, 'Carbondale'),
(38, 'Carlisle'),
(38, 'Carnegie'),
(38, 'Central City'),
(38, 'Chalfont'),
(38, 'Chambersburg'),
(38, 'Clarion'),
(38, 'Clearfield'),
(38, 'Coatesville'),
(38, 'Columbia'),
(38, 'Coopersburg'),
(38, 'Coraopolis'),
(38, 'Cranberry'),
(38, 'Cranberry Township'),
(38, 'Cresco'),
(38, 'Denver'),
(38, 'Devon'),
(38, 'Dillsburg'),
(38, 'Doylestown'),
(38, 'Dravosburg'),
(38, 'Easton'),
(38, 'Ebensburg'),
(38, 'Elizabeth'),
(38, 'Elizabethtown'),
(38, 'Ellwood City'),
(38, 'Ephrata'),
(38, 'Erie'),
(38, 'Exton'),
(38, 'Fairless Hills'),
(38, 'Flourtown'),
(38, 'Folsom'),
(38, 'Frackville'),
(38, 'Gettysburg'),
(38, 'Gibsonia'),
(38, 'Glen Rock'),
(38, 'Glenolden'),
(38, 'Greensburg'),
(38, 'Grindstone'),
(38, 'Grove City'),
(38, 'Hanover'),
(38, 'Harmony'),
(38, 'Harrisburg'),
(38, 'Hatfield'),
(38, 'Haverford'),
(38, 'Hawley'),
(38, 'Hermitage'),
(38, 'Holmes'),
(38, 'Indiana'),
(38, 'Irwin'),
(38, 'Jeannette'),
(38, 'Jim Thorpe'),
(38, 'Johnstown'),
(38, 'Jonestown'),
(38, 'Kennett Square'),
(38, 'Kingston'),
(38, 'Kittanning'),
(38, 'Lancaster'),
(38, 'Lebanon'),
(38, 'Leechburg'),
(38, 'Lehighton'),
(38, 'Lewisburg'),
(38, 'Ligonier'),
(38, 'Littlestown'),
(38, 'Lock Haven'),
(38, 'Mansfield'),
(38, 'McKeesport'),
(38, 'Meadville'),
(38, 'Mechanicsburg'),
(38, 'Mercer'),
(38, 'Meyersdale'),
(38, 'Mifflinburg'),
(38, 'Mifflinville'),
(38, 'Milroy'),
(38, 'Monaca'),
(38, 'Monroeville'),
(38, 'Morrisville'),
(38, 'Mount Pleasant'),
(38, 'Mount Pocono'),
(38, 'Murrysville'),
(38, 'Natrona Heights'),
(38, 'Nesquehoning'),
(38, 'New Castle'),
(38, 'New Holland'),
(38, 'New Hope'),
(38, 'New Oxford'),
(38, 'Norristown'),
(38, 'North Versailles'),
(38, 'Palmyra'),
(38, 'Paoli'),
(38, 'Parkesburg'),
(38, 'Pennsburg'),
(38, 'Perkasie'),
(38, 'Philadelphia'),
(38, 'Philipsburg'),
(38, 'Phoenixville'),
(38, 'Pittsburgh'),
(38, 'Pottstown'),
(38, 'Quakertown'),
(38, 'Reading'),
(38, 'Ridley Park'),
(38, 'Roaring Spring'),
(38, 'Saint Clair'),
(38, 'Saint Marys'),
(38, 'Sayre'),
(38, 'Schuylkill Haven'),
(38, 'Scranton'),
(38, 'Sharon'),
(38, 'Snow Shoe'),
(38, 'Spring Grove'),
(38, 'Springfield'),
(38, 'Temple'),
(38, 'Tidioute'),
(38, 'Titusville'),
(38, 'Trexlertown'),
(38, 'Uniontown'),
(38, 'Upper Darby'),
(38, 'Verona'),
(38, 'Walnutport'),
(38, 'Warren'),
(38, 'Warrington'),
(38, 'Washington'),
(38, 'Waynesboro'),
(38, 'West Chester'),
(38, 'West Mifflin'),
(38, 'West Newton'),
(38, 'Wexford'),
(38, 'Whitehall'),
(38, 'Williamsport'),
(38, 'Willow Grove'),
(38, 'Wyoming'),
(38, 'York'),
(39, 'Cranston'),
(39, 'East Greenwich'),
(39, 'Pawtucket'),
(39, 'Providence'),
(39, 'Warwick'),
(39, 'West Warwick'),
(39, 'Woonsocket'),
(40, 'Aiken'),
(40, 'Allendale'),
(40, 'Anderson'),
(40, 'Aynor'),
(40, 'Beaufort'),
(40, 'Belton'),
(40, 'Bishopville'),
(40, 'Blythewood'),
(40, 'Boiling Springs'),
(40, 'Camden'),
(40, 'Central'),
(40, 'Charleston'),
(40, 'Clemson'),
(40, 'Clover'),
(40, 'Columbia'),
(40, 'Conway'),
(40, 'Darlington'),
(40, 'Dillon'),
(40, 'Duncan'),
(40, 'Easley'),
(40, 'Enoree'),
(40, 'Florence'),
(40, 'Fort Mill'),
(40, 'Fountain Inn'),
(40, 'Gaffney'),
(40, 'Gaston'),
(40, 'Gilbert'),
(40, 'Goose Creek'),
(40, 'Greenville'),
(40, 'Greenwood'),
(40, 'Greer'),
(40, 'Hartsville'),
(40, 'Hilton Head Island'),
(40, 'Irmo'),
(40, 'Johnsonville'),
(40, 'Kingstree'),
(40, 'Lake City'),
(40, 'Lancaster'),
(40, 'Landrum'),
(40, 'Laurens'),
(40, 'Lexington'),
(40, 'Liberty'),
(40, 'Lugoff'),
(40, 'Mauldin'),
(40, 'Moncks Corner'),
(40, 'Mount Pleasant'),
(40, 'Mullins'),
(40, 'Murrells Inlet'),
(40, 'Myrtle Beach'),
(40, 'Newberry'),
(40, 'North Augusta'),
(40, 'North Charleston'),
(40, 'North Myrtle Beach'),
(40, 'Orangeburg'),
(40, 'Pendleton'),
(40, 'Pickens'),
(40, 'Piedmont'),
(40, 'Ridgeland'),
(40, 'Rock Hill'),
(40, 'Saint George'),
(40, 'Simpsonville'),
(40, 'Spartanburg'),
(40, 'Summerville'),
(40, 'Sumter'),
(40, 'Timmonsville'),
(40, 'Union'),
(40, 'Walhalla'),
(40, 'Walterboro'),
(40, 'West Columbia'),
(40, 'Williamston'),
(40, 'York'),
(41, 'Aberdeen'),
(41, 'Brookings'),
(41, 'Chamberlain'),
(41, 'Hot Springs'),
(41, 'Huron'),
(41, 'Mitchell'),
(41, 'Mobridge'),
(41, 'Oacoma'),
(41, 'Pierre'),
(41, 'Rapid City'),
(41, 'Sioux Falls'),
(41, 'Spearfish'),
(41, 'Vermillion'),
(41, 'Watertown'),
(41, 'Winner')

INSERT INTO dbo.Zones (cityId, [name])
VALUES
(42, 'Antioch'),
(42, 'Arlington'),
(42, 'Athens'),
(42, 'Blountville'),
(42, 'Bolivar'),
(42, 'Brentwood'),
(42, 'Bristol'),
(42, 'Brownsville'),
(42, 'Bulls Gap'),
(42, 'Camden'),
(42, 'Chattanooga'),
(42, 'Church Hill'),
(42, 'Clarksville'),
(42, 'Cleveland'),
(42, 'Clinton'),
(42, 'Collierville'),
(42, 'Columbia'),
(42, 'Cookeville'),
(42, 'Cordova'),
(42, 'Cornersville'),
(42, 'Crossville'),
(42, 'Dayton'),
(42, 'Decherd'),
(42, 'Dickson'),
(42, 'Dunlap'),
(42, 'Dyersburg'),
(42, 'Elizabethton'),
(42, 'Franklin'),
(42, 'Gainesboro'),
(42, 'Gallatin'),
(42, 'Gatlinburg'),
(42, 'Germantown'),
(42, 'Goodlettsville'),
(42, 'Gordonsville'),
(42, 'Greeneville'),
(42, 'Hartsville'),
(42, 'Henderson'),
(42, 'Hendersonville'),
(42, 'Hermitage'),
(42, 'Hixson'),
(42, 'Humboldt'),
(42, 'Jackson'),
(42, 'Jefferson City'),
(42, 'Johnson City'),
(42, 'Jonesborough'),
(42, 'Kingsport'),
(42, 'Kingston Springs'),
(42, 'Knoxville'),
(42, 'Lawrenceburg'),
(42, 'Lebanon'),
(42, 'Lenoir City'),
(42, 'Livingston'),
(42, 'Loretto'),
(42, 'Louisville'),
(42, 'Lynchburg'),
(42, 'Madison'),
(42, 'Martin'),
(42, 'Maryville'),
(42, 'McMinnville'),
(42, 'Memphis'),
(42, 'Milan'),
(42, 'Millington'),
(42, 'Morristown'),
(42, 'Mount Juliet'),
(42, 'Murfreesboro'),
(42, 'Nashville'),
(42, 'Newport'),
(42, 'Oak Ridge'),
(42, 'Oakland'),
(42, 'Ocoee'),
(42, 'Old Hickory'),
(42, 'Oneida'),
(42, 'Ooltewah'),
(42, 'Paris'),
(42, 'Pigeon Forge'),
(42, 'Piney Flats'),
(42, 'Portland'),
(42, 'Powell'),
(42, 'Pulaski'),
(42, 'Sevierville'),
(42, 'Seymour'),
(42, 'Shelbyville'),
(42, 'Signal Mountain'),
(42, 'Smithville'),
(42, 'Smyrna'),
(42, 'Spring Hill'),
(42, 'Springfield'),
(42, 'Sweetwater'),
(42, 'Tullahoma'),
(42, 'Union City'),
(42, 'Watertown'),
(42, 'White House'),
(42, 'Winchester'),
(42, 'Woodbury'),
(43, 'Abilene'),
(43, 'Alice'),
(43, 'Allen'),
(43, 'Alvin'),
(43, 'Amarillo'),
(43, 'Angleton'),
(43, 'Arlington'),
(43, 'Athens'),
(43, 'Atlanta'),
(43, 'Austin'),
(43, 'Azle'),
(43, 'Bastrop'),
(43, 'Bay City'),
(43, 'Baytown'),
(43, 'Beaumont'),
(43, 'Bedford'),
(43, 'Beeville'),
(43, 'Bellaire'),
(43, 'Big Spring'),
(43, 'Boerne'),
(43, 'Bonham'),
(43, 'Borger'),
(43, 'Bowie'),
(43, 'Brazoria'),
(43, 'Bridge City'),
(43, 'Brookshire'),
(43, 'Brownsville'),
(43, 'Bryan'),
(43, 'Buda'),
(43, 'Buna'),
(43, 'Burkburnett'),
(43, 'Burleson'),
(43, 'Cameron'),
(43, 'Canton'),
(43, 'Canyon'),
(43, 'Carrizo Springs'),
(43, 'Carrollton'),
(43, 'Cedar Hill'),
(43, 'Cedar Park'),
(43, 'Childress'),
(43, 'Cleburne'),
(43, 'Cleveland'),
(43, 'Clifton'),
(43, 'Colorado City'),
(43, 'Conroe'),
(43, 'Converse'),
(43, 'Copperas Cove'),
(43, 'Corpus Christi'),
(43, 'Corrigan'),
(43, 'Corsicana'),
(43, 'Cresson'),
(43, 'Cuero'),
(43, 'Cypress'),
(43, 'Daingerfield'),
(43, 'Dallas'),
(43, 'Decatur'),
(43, 'Deer Park'),
(43, 'Del Rio'),
(43, 'Denison'),
(43, 'Denton'),
(43, 'Dripping Springs'),
(43, 'Dumas'),
(43, 'Duncanville'),
(43, 'Eagle Pass'),
(43, 'Early'),
(43, 'East Bernard'),
(43, 'Eastland'),
(43, 'Eden'),
(43, 'Edinburg'),
(43, 'Edna'),
(43, 'El Campo'),
(43, 'El Paso'),
(43, 'Elsa'),
(43, 'Ennis'),
(43, 'Flower Mound'),
(43, 'Forney'),
(43, 'Fort Worth'),
(43, 'Fredericksburg'),
(43, 'Freeport'),
(43, 'Friendswood'),
(43, 'Frisco'),
(43, 'Gainesville'),
(43, 'Garland'),
(43, 'Georgetown'),
(43, 'Gilmer'),
(43, 'Glen Rose'),
(43, 'Grand Prairie'),
(43, 'Grapevine'),
(43, 'Hamilton'),
(43, 'Harker Heights'),
(43, 'Harlingen'),
(43, 'Harrold'),
(43, 'Haskell'),
(43, 'Hereford'),
(43, 'Hidalgo'),
(43, 'Hitchcock'),
(43, 'Houston'),
(43, 'Humble'),
(43, 'Huntington'),
(43, 'Huntsville'),
(43, 'Hurst'),
(43, 'Ingleside'),
(43, 'Irving'),
(43, 'Katy'),
(43, 'Keller'),
(43, 'Kemah'),
(43, 'Kenedy'),
(43, 'Kermit'),
(43, 'Kerrville'),
(43, 'Killeen'),
(43, 'Kingwood'),
(43, 'Kyle'),
(43, 'La Feria'),
(43, 'La Grange'),
(43, 'La Marque'),
(43, 'La Porte'),
(43, 'La Vernia'),
(43, 'Laredo'),
(43, 'League City'),
(43, 'Leander'),
(43, 'Lewisville'),
(43, 'Little Elm'),
(43, 'Longview'),
(43, 'Lubbock'),
(43, 'Lufkin'),
(43, 'Lumberton'),
(43, 'Mabank'),
(43, 'Madisonville'),
(43, 'Mansfield'),
(43, 'Manvel'),
(43, 'Marlin'),
(43, 'McAllen'),
(43, 'McKinney'),
(43, 'Mesquite'),
(43, 'Midland'),
(43, 'Mineral Wells'),
(43, 'Mission'),
(43, 'Missouri City'),
(43, 'Monahans'),
(43, 'Mount Pleasant'),
(43, 'Mount Vernon'),
(43, 'Nederland'),
(43, 'New Braunfels'),
(43, 'North Richland Hills'),
(43, 'Odessa'),
(43, 'Palestine'),
(43, 'Paris'),
(43, 'Pasadena'),
(43, 'Pearland'),
(43, 'Penitas'),
(43, 'Pettus'),
(43, 'Pflugerville'),
(43, 'Pittsburg'),
(43, 'Plano'),
(43, 'Pleasanton'),
(43, 'Port Arthur'),
(43, 'Port Lavaca'),
(43, 'Portland'),
(43, 'Princeton'),
(43, 'Ranger'),
(43, 'Red Oak'),
(43, 'Refugio'),
(43, 'Richardson'),
(43, 'Richmond'),
(43, 'Rockwall'),
(43, 'Rosenberg'),
(43, 'Round Rock'),
(43, 'Rowlett'),
(43, 'Rusk'),
(43, 'Sachse'),
(43, 'San Angelo'),
(43, 'San Antonio'),
(43, 'San Diego'),
(43, 'San Marcos'),
(43, 'Sanger'),
(43, 'Santa Fe'),
(43, 'Schertz'),
(43, 'Schulenburg'),
(43, 'Seabrook'),
(43, 'Seagoville'),
(43, 'Seguin'),
(43, 'Seminole'),
(43, 'Seymour'),
(43, 'Sherman'),
(43, 'Sinton'),
(43, 'Snyder'),
(43, 'South Padre Island'),
(43, 'Southlake'),
(43, 'Spring'),
(43, 'Spring Branch'),
(43, 'Sugar Land'),
(43, 'Sulphur Springs'),
(43, 'Sweetwater'),
(43, 'Temple'),
(43, 'Terrell'),
(43, 'Texarkana'),
(43, 'Texas City'),
(43, 'Tivoli'),
(43, 'Tomball'),
(43, 'Tyler'),
(43, 'Uvalde'),
(43, 'Van'),
(43, 'Victoria'),
(43, 'Waco'),
(43, 'Waller'),
(43, 'Waxahachie'),
(43, 'Weatherford'),
(43, 'Webster'),
(43, 'Weslaco'),
(43, 'Wharton'),
(43, 'Whitehouse'),
(43, 'Whitesboro'),
(43, 'Wichita Falls'),
(43, 'Willis'),
(43, 'Winnsboro'),
(43, 'Woodville'),
(43, 'Wylie'),
(44, 'American Fork'),
(44, 'Brigham City'),
(44, 'Cedar City'),
(44, 'Draper'),
(44, 'Hurricane'),
(44, 'Kaysville'),
(44, 'Layton'),
(44, 'Lehi'),
(44, 'Lindon'),
(44, 'Magna'),
(44, 'Ogden'),
(44, 'Orem'),
(44, 'Park City'),
(44, 'Price'),
(44, 'Provo'),
(44, 'Riverton'),
(44, 'Roy'),
(44, 'Salt Lake City'),
(44, 'Sandy'),
(44, 'Saratoga Springs'),
(44, 'Spanish Fork'),
(44, 'Springville'),
(44, 'West Jordan'),
(44, 'West Valley City'),
(45, 'Abingdon'),
(45, 'Alexandria'),
(45, 'Annandale'),
(45, 'Arlington'),
(45, 'Bedford'),
(45, 'Burke'),
(45, 'Carrollton'),
(45, 'Chantilly'),
(45, 'Charlottesville'),
(45, 'Chesapeake'),
(45, 'Christiansburg'),
(45, 'Collinsville'),
(45, 'Colonial Heights'),
(45, 'Culpeper'),
(45, 'Daleville'),
(45, 'Danville'),
(45, 'Disputanta'),
(45, 'Dublin'),
(45, 'Dumfries'),
(45, 'Elkton'),
(45, 'Emporia'),
(45, 'Exmore'),
(45, 'Fairfax'),
(45, 'Falls Church'),
(45, 'Farmville'),
(45, 'Fort Belvoir'),
(45, 'Fredericksburg'),
(45, 'Gloucester'),
(45, 'Gordonsville'),
(45, 'Hampton'),
(45, 'Harrisonburg'),
(45, 'Hayes'),
(45, 'Henrico'),
(45, 'Herndon'),
(45, 'Hopewell'),
(45, 'King George'),
(45, 'Lambsburg'),
(45, 'Lawrenceville'),
(45, 'Leesburg'),
(45, 'Lexington'),
(45, 'Luray'),
(45, 'Lynchburg'),
(45, 'Madison Heights'),
(45, 'Manassas'),
(45, 'Marion'),
(45, 'Martinsville'),
(45, 'Mechanicsville'),
(45, 'Midlothian'),
(45, 'New Market'),
(45, 'Newport News'),
(45, 'Norfolk'),
(45, 'Palmyra'),
(45, 'Petersburg'),
(45, 'Poquoson'),
(45, 'Portsmouth'),
(45, 'Powhatan'),
(45, 'Providence Forge'),
(45, 'Pulaski'),
(45, 'Radford'),
(45, 'Reston'),
(45, 'Richlands'),
(45, 'Richmond'),
(45, 'Ridgeway'),
(45, 'Roanoke'),
(45, 'Rocky Mount'),
(45, 'Rustburg'),
(45, 'Ruther Glen'),
(45, 'Salem'),
(45, 'Smithfield'),
(45, 'South Boston'),
(45, 'Spotsylvania'),
(45, 'Springfield'),
(45, 'Suffolk'),
(45, 'Troutville'),
(45, 'Vienna'),
(45, 'Vinton'),
(45, 'Virginia Beach'),
(45, 'Warrenton'),
(45, 'Waynesboro'),
(45, 'Williamsburg'),
(45, 'Winchester'),
(45, 'Wise'),
(45, 'Woodbridge'),
(45, 'Woodstock'),
(45, 'Wytheville'),
(45, 'Yorktown'),
(46, 'Burlington'),
(46, 'Colchester'),
(46, 'Enosburg Falls'),
(46, 'Essex Junction'),
(46, 'Rutland'),
(46, 'Saint Albans'),
(46, 'South Burlington'),
(46, 'Williston'),
(47, 'Aberdeen'),
(47, 'Auburn'),
(47, 'Bellevue'),
(47, 'Bellingham'),
(47, 'Burlington'),
(47, 'Centralia'),
(47, 'Chehalis'),
(47, 'Clarkston'),
(47, 'Cle Elum'),
(47, 'East Wenatchee'),
(47, 'Enumclaw'),
(47, 'Ephrata'),
(47, 'Everett'),
(47, 'Federal Way'),
(47, 'Issaquah'),
(47, 'Kennewick'),
(47, 'Kent'),
(47, 'Lacey'),
(47, 'Lakewood'),
(47, 'Leavenworth'),
(47, 'Liberty Lake'),
(47, 'Long Beach'),
(47, 'Longview'),
(47, 'Lynnwood'),
(47, 'Marysville'),
(47, 'Moses Lake'),
(47, 'Mount Vernon'),
(47, 'North Bend'),
(47, 'Olympia'),
(47, 'Pasco'),
(47, 'Port Angeles'),
(47, 'Port Orchard'),
(47, 'Prosser'),
(47, 'Pullman'),
(47, 'Puyallup'),
(47, 'Redmond'),
(47, 'Renton'),
(47, 'Richland'),
(47, 'Seattle'),
(47, 'Selah'),
(47, 'Sequim'),
(47, 'Shelton'),
(47, 'Silverdale'),
(47, 'Snohomish'),
(47, 'Spokane'),
(47, 'Tacoma'),
(47, 'Toppenish'),
(47, 'Vancouver'),
(47, 'Veradale'),
(47, 'Walla Walla'),
(47, 'Woodinville'),
(47, 'Woodland'),
(47, 'Yakima'),
(47, 'Yelm'),
(48, 'Appleton'),
(48, 'Beaver Dam'),
(48, 'Belgium'),
(48, 'Beloit'),
(48, 'Bristol'),
(48, 'Brookfield'),
(48, 'Cedarburg'),
(48, 'Chetek'),
(48, 'Chippewa Falls'),
(48, 'Clintonville'),
(48, 'De Pere'),
(48, 'Delafield'),
(48, 'Delavan'),
(48, 'Eau Claire'),
(48, 'Fond du Lac'),
(48, 'Franklin'),
(48, 'Fremont'),
(48, 'Germantown'),
(48, 'Grafton'),
(48, 'Green Bay'),
(48, 'Hales Corners'),
(48, 'Jackson'),
(48, 'Janesville'),
(48, 'Johnson Creek'),
(48, 'Kenosha'),
(48, 'Kewaskum'),
(48, 'La Crosse'),
(48, 'Lake Geneva'),
(48, 'Lancaster'),
(48, 'Little Chute'),
(48, 'Madison'),
(48, 'Manitowoc'),
(48, 'Marshfield'),
(48, 'Menasha'),
(48, 'Menomonie'),
(48, 'Middleton'),
(48, 'Milton'),
(48, 'Milwaukee'),
(48, 'Minocqua'),
(48, 'Mosinee'),
(48, 'Mukwonago'),
(48, 'Muskego'),
(48, 'Nashotah'),
(48, 'Neenah'),
(48, 'New Franken'),
(48, 'New Holstein'),
(48, 'New London'),
(48, 'Oak Creek'),
(48, 'Oconto Falls'),
(48, 'Oshkosh'),
(48, 'Platteville'),
(48, 'Plover'),
(48, 'Port Washington'),
(48, 'Portage'),
(48, 'Racine'),
(48, 'Reedsburg'),
(48, 'Rhinelander'),
(48, 'Rice Lake'),
(48, 'Richland Center'),
(48, 'Ripon'),
(48, 'River Falls'),
(48, 'Rothschild'),
(48, 'Sauk City'),
(48, 'Shawano'),
(48, 'Sheboygan'),
(48, 'Sheboygan Falls'),
(48, 'Sun Prairie'),
(48, 'Tomah'),
(48, 'Two Rivers'),
(48, 'Union Grove'),
(48, 'Viroqua'),
(48, 'Watertown'),
(48, 'Waukesha'),
(48, 'Waunakee'),
(48, 'Wausau'),
(48, 'Wautoma'),
(48, 'West Bend'),
(48, 'Westfield'),
(48, 'Whitewater'),
(48, 'Wisconsin Dells'),
(48, 'Wisconsin Rapids'),
(49, 'Beckley'),
(49, 'Bluefield'),
(49, 'Bridgeport'),
(49, 'Buckhannon'),
(49, 'Caldwell'),
(49, 'Charles Town'),
(49, 'Charleston'),
(49, 'Clarksburg'),
(49, 'Elkins'),
(49, 'Elkview'),
(49, 'Fairmont'),
(49, 'Follansbee'),
(49, 'Grafton'),
(49, 'Huntington'),
(49, 'Inwood'),
(49, 'Kingwood'),
(49, 'Lewisburg'),
(49, 'Logan'),
(49, 'Martinsburg'),
(49, 'Milton'),
(49, 'Morgantown'),
(49, 'Moundsville'),
(49, 'Parkersburg'),
(49, 'Petersburg'),
(49, 'Point Pleasant'),
(49, 'Princeton'),
(49, 'Ripley'),
(49, 'Saint Marys'),
(49, 'South Charleston'),
(49, 'Summersville'),
(49, 'Triadelphia'),
(49, 'Weirton'),
(49, 'Welch'),
(49, 'Wellsburg'),
(49, 'Weston'),
(49, 'Wheeling'),
(50, 'Afton'),
(50, 'Casper'),
(50, 'Cheyenne'),
(50, 'Cody'),
(50, 'Evanston'),
(50, 'Gillette'),
(50, 'Green River'),
(50, 'Laramie'),
(50, 'Powell'),
(50, 'Riverton'),
(50, 'Rock Springs'),
(50, 'Sheridan'),
(50, 'Thermopolis'),
(50, 'Wheatland')